### ISSUE TITLE
Tagged 14.1 without updating pom.xml

### ISSUE THREAD

**Issue by FireBurn** [OpenIdentityPlatform/OpenAM#10]
Hi

You've tagged 14.1.0 without updating the pom.xml file accordingly

There should probably be a commit that fixes the pom.xml, that then tagged with a release number, then a follow up commit changing the versions to dev SNAPSHOTS

Cheers

Mike

**Comment by FireBurn** [comment]
Also that commit should update the submodules to the correct commits, this can probably be scripted

**Comment by vharseko** [comment]
This is fake tag, for 14.1.0+1=14.1.1 automatic feature build
View https://github.com/OpenIdentityPlatform/OpenAM/blob/aacc88a093d9f15b1c4b8daf9b166b2e4826866c/.travis.yml#L72

**Comment by vharseko** [comment]
fixed
