### ISSUE TITLE
XUI Not Default

### ISSUE THREAD

**Issue by FireBurn** [OpenIdentityPlatform/OpenAM#12]
It seems most of the pages are stuck on the old UI rather than XUI

I can't seem to create policies properly in a realm

**Comment by vharseko** [comment]
* by default XUI console switched "off" (need !HttpOnly cookie token)
* policy editor work in old style UI console (tab Access control - (Top Level Realm) - Policies)
* for using XUI console, goto /amserver/XUI/?realm=/#realms/%2F/authorization-resourceTypes and re-authetntificate with !HttpOnly cookie token

**Comment by vharseko** [comment]
@maximthomas ?:
1. add two links in headers for switch "Old"<->"New"
2. System property for "disable XUI"
3. Rollback and Enable XUI by default

**Comment by vharseko** [comment]
from https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/14.1.3
please read https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-disable-XUI-by-default
