### ISSUE TITLE
IDP SLO Request don't have KeyInfo Tag

### ISSUE THREAD

**Issue by viruls** [OpenIdentityPlatform/OpenAM#120]
Dear Experts,

I triggered SAML SLO Request from IDP and In the SLO Request where I don't see the tag <ds:KeyInfo> . Is this expected with OpenAM, Please advise?

![image](https://user-images.githubusercontent.com/1412321/50758034-f9b30280-129b-11e9-84df-d2af567fc3b4.png)

Please find the attached HTTP Trace for your reference.

[slo_idp_init.txt](https://github.com/OpenIdentityPlatform/OpenAM/files/2732003/slo_idp_init.txt)

attached Fiddler trace as well, rename the slo_idp_init.txt to slo_idp_init.saz 

Thanks,

**Comment by viruls** [comment]
Any update please ?

**Comment by vharseko** [comment]
please check https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/14.8.2
