### ISSUE TITLE
New Auth Modules can not be enabled in the Docker image

### ISSUE THREAD

**Issue by deftdawg** [OpenIdentityPlatform/OpenAM#15]
When attempting to enable a new module instance in the docker image (OpenAM 14.1.1 Build 2f3d35c4a1 (2018-April-28 10:03)), following the steps to add and provide any optional configuration values (such as datastore for HTTP Basic Auth), the modules do not appear in the list of enabled modules and can not be used in an authentication chain.

Steps to reproduce:
1. Deploy to docker
2. Create a default repo
3. Login as amAdmin
4. Go to Realms tab -> select (Top Level Realm) -> Authentication tab -> Module Instances, click "New" -> add an authentication module -> save

The module does not appear in the module instances and can't be used in the Authentication chaining.
Tried with both non-XUI and XUI UI modes.

The above steps worked as expected on "OpenAM 11.0.3 Community Edition" built from source.

**Comment by vharseko** [comment]
after the restart of the service, the created modules are available in the list?

**Comment by deftdawg** [comment]
This issue is back for 14.1.5, this issue should be reopened.
@maximthomas, was there a particular reason why you reverted @vharseko's fix?
