### ISSUE TITLE
DeviceID

### ISSUE THREAD

**Issue by diegogmanzanares** [OpenIdentityPlatform/OpenAM#150]
Hi,

I configure a test realm with ldap authenticacion, and this work correctly validating with the uid and the email address.
Now I add the modules the deviceID to the chain, but if I validate with the email, the device is not saved and no show in the dashboard.
If I validate with the uid all work correctly.

Is posible modify the code to work correctly with all login attributes (uid, mail ...)

Thanks.

**Comment by diegogmanzanares** [comment]
the version of openam is 14.2.2

**Comment by vharseko** [comment]
please provide step by step instruction for reproduce
