### ISSUE TITLE
Unable to upload metadata file reside ?

### ISSUE THREAD

**Issue by vasim-farooqui** [OpenIdentityPlatform/OpenAM#165]
Cannot Upload metadata file while configuring SAMLv2 Remote Service provider.

![image](https://user-images.githubusercontent.com/36871383/63454284-22bd8780-c468-11e9-9550-e3e2cd3c4ef7.png)

**Comment by maximthomas** [comment]
@vasim-farooqui what error message you got after pressing upload? Can you attach sample sp-metatata.xml file and openam logs to the issue?

**Comment by maximthomas** [comment]
@vasim-farooqui, are you still facing the issue? could you provide feedback?
