### ISSUE TITLE
OpenAM Community archive is not public

### ISSUE THREAD

**Issue by boucman** [OpenIdentityPlatform/OpenAM#166]
**Describe the bug**
The  page https://groups.google.com/forum/#!forum/open-identity-platform-openam is documented in README.md as the archive of the OpenAM mailing list.

However, it is not possible to access that page (might be possible if logged in with a google account registered to the ML, I havn't tried)

This is most likely a configuration option on the googlegroup page

thx, and sorry if this is not the right place to report that.
Boucman

**Comment by vharseko** [comment]
Thanks, fixed view permission

**Comment by boucman** [comment]
Thx a lot, you're fast....

It's better, it seems I can now subscribe, but I can't view the archive is that on purpose (security ML) ?

**Comment by vharseko** [comment]
please check https://cdn.rawgit.com/wiki/OpenIdentityPlatform/OpenAM/old/OpenAM-13.5-Admin-Guide.pdf

**Comment by boucman** [comment]
(I'm not sure how the OpenAM admin guide is related to my issue) 
What I mean is that the google-group does not offer read-access to the mailing-list archive unless you are subscribed. 

If that's on purpose, that's fine, I just wanted to make sur it was not a misconfiguration. I have subscribed, so i'm fine, just making sure...
