### ISSUE TITLE
Wrong link for OAuth 2.0 in Realm > Applications menu

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM#174]
Just a minor bug in the main Applications menu on the left in the admin console. When clicking the "OAuth 2.0" item it redirects to the "Agents/Web Service Client" tab instead of the correct "Agents/OAuth 2.0/OpenID Connect Client" tab.

**To Reproduce**
1. Login to OpenAM Console (OpenAM-14.4.2-SNAPSHOT build from master as of today)
2. Enter any realm
2. Expand the Applications section in the left menu
3. Click "OAuth 2.0"
4. You will get redirected to the tab page "Agents/Web Service Client".

**Expected behavior**
The "OAuth 2.0/OpenID Connect Client" tab page should be presented.

**Desktop (please complete the following information):**
 - OS/Browser: Windows+Chrome/Ubuntu Linux+Firefox
 - Version Latest

**Comment by maximthomas** [comment]
@lscorcia Hi, check the latest sources, the issue has been fixed
