### ISSUE TITLE
ReCaptcha module does not work

### ISSUE THREAD

**Issue by volodyad** [OpenIdentityPlatform/OpenAM#180]
We have configured and added ReCaptcha module to the auth chain

When login page loaded it shows 'Are you human?' question and a text input
When you type anything in this filed and click submit it show error in network:
page not found http://openam.sp.com:8080/openam/XUI/templates/openam/authn/ReCaptcha1.html?v=14.4.1

How could we configure this module properly?

**Comment by maximthomas** [comment]
@volodyad, hi, this module does not work in XUI yet, only in the old UI. We have plans to release it in future.

**Comment by volodyad** [comment]
Which version of openam supports this module ? 
Do you know any external openam captcha modules like https://github.com/mirzlab/openam-recaptcha-module?

**Comment by maximthomas** [comment]
At least since 14.1.14 OpenAM release

**Comment by volodyad** [comment]
Hello,
Thank you for you answers

When it is expected to have this module fixes?

**Comment by maximthomas** [comment]
Hello,
We don't have plans about this module yet, I'll fix the module, when I will have more free time and let you know
