### ISSUE TITLE
Unclear how to build from source or build from README does not work

### ISSUE THREAD

**Issue by EvilLord666** [OpenIdentityPlatform/OpenAM#186]
I am trying to build OpenAM from source according to  list of commands from README file and got errors during build

1. It was not mentioned what working directory should be because root dir (dir that contains .git folder) when i cloned repo does not have direcory OpenAM therefore:

mvn -DskipTests -Dmaven.javadoc.skip=true install -f OpenAm/OpenDJ/forgerock-parent
should be transformed to mvn -DskipTests -Dmaven.javadoc.skip=true install -f OpenDJ/forgerock-parent

2. When i am running this command i am getting an error:

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\maven-external-dependency-plugin\maven-external-dependency-plugin of C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\pom.xml does not exist @
[ERROR] Child module C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\forgerock-i18n-framework\pom.xml of C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\pom.xml does not exist @
[ERROR] Child module C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\forgerock-guice\pom.xml of C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\pom.xml does not exist @
[ERROR] Child module C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\forgerock-ui\pom.xml of C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\pom.xml does not exist @
[ERROR] Child module C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\forgerock-persistit\pom.xml of C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\pom.xml does not exist @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.forgerock:forgerock-parent:2.0.6 (C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\pom.xml) has 5 errors
[ERROR]     Child module C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\maven-external-dependency-plugin\maven-external-dependency-plugin of C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\pom.xml does not exist
[ERROR]     Child module C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\forgerock-i18n-framework\pom.xml of C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\pom.xml does not exist
[ERROR]     Child module C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\forgerock-guice\pom.xml of C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\pom.xml does not exist
[ERROR]     Child module C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\forgerock-ui\pom.xml of C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\pom.xml does not exist
[ERROR]     Child module C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\forgerock-persistit\pom.xml of C:\Users\michael\Projects\opensource\OpenAM\OpenDJ\forgerock-parent\pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

The problem is due to  child .pom's does not exists.

OS: Win10 x64

**Comment by vharseko** [comment]
please clone with --recursive switch

**Comment by EvilLord666** [comment]
Unfortunately i am not able to properly clone submodule due to "...Filename is too Long..." message
However i've already set git config option that is responsible for long names and Windows registry key (\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathEnabled) with value of 1.

**Comment by vharseko** [comment]
use
```
git config --system core.longpaths true
```

**Comment by EvilLord666** [comment]
Yes i did as i mentioned above simulteneously with filesystem setting, but still couldn't clone submodule
my git version is: git version 2.17.1.windows.2

git config --system -l
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
credential.helper=manager
core.longpaths=true

**Comment by vharseko** [comment]
If you have Windows 10 Pro or Enterprise you could also use Local Group Policies.

Go to Computer Configuration → Administrative Templates → System → Filesystem in gpedit.msc, open Enable Win32 long paths and set it to Enabled.
