### ISSUE TITLE
Chain with LDAP and HOTP module does not work

### ISSUE THREAD

**Issue by volodyad** [OpenIdentityPlatform/OpenAM#187]
Openam 14.4.1
User default settings
Add one chain with LDAP and HOTP module
LDAP module setup to use mail for auth
HOTP module to send email

Steps to reproduce
1) Create test users with ( firstName test, lastName test, email test@mail.com )
2) Go to login screen
3) Login via mail and ldap password
4) Navigate to HOTP module
5) Click request OTP

Actual result: app crashes

error: An error occurred while sending the One Time Password. Please contact the system administrator. {message: "An error occurred while sending the One Time Password. Please contact the system administrator.", type: "error"}

Logs ERROR: HTOP:getIdentity : User test@mail.com is not found

**Comment by volodyad** [comment]
resolve this issue by adding 'mail' to the field - Alias Search Attribute Name
under Authentication -> Settings -> UserProfile

**Comment by vharseko** [comment]
add 'mail' to the field - Alias Search Attribute Name
under Authentication -> Settings -> UserProfile
