### ISSUE TITLE
User session error when login

### ISSUE THREAD

**Issue by volodyad** [OpenIdentityPlatform/OpenAM#188]
Steps to reproduce
Login to openam
wait for a day
open login page

Results: it shows 401 for request https://openam:18443/openam/json/users?_action=idFromSession
Screen shows error 'Authentication Error!!'

2. When i deleted session cookie and tried again navigate to login page it returns 500 error for https://openam:18443/openam/json/realms/root/authenticate
and logs shows
amAuth:09/26/2019 06:45:38:471 AM UTC: Thread[https-openssl-nio-18443-exec-10,5,main]: TransactionId[da0baa13-e1a2-4b85-9097-070b384e5893-3891]
ERROR: Error in populateOrgProfile
Message:Invalid SSO Token: Invalid SSO Token 
at com.sun.identity.sm.OrganizationConfigManager.getServiceConfig(OrganizationConfigManager.java:1188)
	at com.sun.identity.authentication.service.LoginState.populateOrgProfile(LoginState.java:672)
	at com.sun.identity.authentication.service.LoginState.createAuthContext(LoginState.java:1775)

**Comment by spetix** [comment]
this looks very similar to #201

**Comment by spetix** [comment]
it seems still present in version 14.5.1

**Comment by vharseko** [comment]
cannot reproduce in 14.5.4
