### ISSUE TITLE
Build from source on Ubuntu 18.04

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM#197]
Hi, I had some troubles when setting up a fresh Ubuntu 18.04.3 VM to build the current sources.
Steps:
* Install Ubuntu 18.04.3, apt update && apt upgrade, reboot
* Install git, openjdk-8-jdk and maven, reboot
* Build according to instructions:
  * git clone sources
  * Build ForgeRock Parent -> success
  * Build OpenDJ -> success
  * Build OpenAM -> fail

The reported error was `Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (generate-idsvcs-source) on project openam-idsvcs-schema: An Ant BuildException has occured: Java returned: 1[ERROR] around Ant part ...<java fork="true" classname="com.sun.xml.rpc.tools.wscompile.Main" failonerror="true" classpathref="wscompile.path">... @ 11:119 in /home/luca/OpenAM/openam-schema/openam-idsvcs-schema/target/antrun/build-idsvcs.xml`

A few lines above, the real error reason: `"idsvcs" java error - com.sun.tools.javac.Main is not available in the classpath`.

To fix this, I had to manually set the JAVA_HOME variable in the /etc/environment file and export the PATH variable as $PATH:$JAVA_HOME/bin in the ~/.bashrc file, then reboot.

Now, I'm no java expert but if the other build steps don't need those variables then probably there's some mistake in the build definition, but since it's so easy to fix it I think that documenting these requirements in the readme.md should be enough.

**Comment by maximthomas** [comment]
Hi, could you attach full maven log to the issue?

**Comment by lscorcia** [comment]
Hi Maxim,
here is the build log captured using the tee command. Please let me know if you were referring to any other process specific log. 
Thanks in advance

[OpenAM.log](https://github.com/OpenIdentityPlatform/OpenAM/files/3858711/OpenAM.log)

**Comment by maximthomas** [comment]
Thanks, could you also provide output of `mvn -version` command?

**Comment by lscorcia** [comment]
Sure!

luca@luca-vm:~$ mvn -version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_222, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-36-generic", arch: "amd64", family: "unix"

**Comment by maximthomas** [comment]
Hi Luca, 
Seems you are using jre instead jdk, try to use  `/usr/lib/jvm/java-8-openjdk-amd64` instead `/usr/lib/jvm/java-8-openjdk-amd64/jre`

**Comment by maximthomas** [comment]
@lscorcia Hi, 
Is the problem solved?

**Comment by lscorcia** [comment]
Hi Maxim, sorry for the delay. With the help of your questions, I discovered that the Ubuntu OpenJDK packages do not set JAVA_HOME during setup and they don't register an entry with the `update-alternatives` command either. 
When JAVA_HOME is undefined, Maven tries to autodetect JAVA_HOME by executing the command `which java`, which returns `/usr/bin/java` , a symlink pointing to `/etc/alternatives/java` , which in turn points to the JRE folder. I might be wrong, but it seems like there is no other built-in alternative to manually define the JAVA_HOME variable. This means that the project code is fine as it is and I will close the issue, but maybe a specific reminder could be added to the build instructions in the readme anyway. 

Thanks for your help!
