### ISSUE TITLE
Where are the logs in the docker image?

### ISSUE THREAD

**Issue by nicholasamorim** [OpenIdentityPlatform/OpenAM#214]
I know there are logs in `/usr/local/tomcat/logs` but there has to be surely more?

I'm having trouble setting up SSO using OpenAM as IDP and my application as SP. There's always an error after the login - on the redirect step. It is very opaque: `Unable to do Single Sign On or Federation.`

I've checked metadata, entity IDs, certificate values, etc but nothing seems wrong. The internet keeps saying to check "the federation debug logs".

Where are those logs?

**Comment by maximthomas** [comment]
Take a look at `/usr/openam/config/<your instance>/logs` folder

**Comment by nicholasamorim** [comment]
Thanks!

For future reference, the federation debug logs are actually in `/usr/openam/config/<your instance>/debug/Federation`
