### ISSUE TITLE
Reaper cause AM to hang when huge sessions timeout together

### ISSUE THREAD

**Issue by barramandi** [OpenIdentityPlatform/OpenAM#216]
**Describe the bug**

**To Reproduce**
1. Set idle and max timeout to short time like 5mins or just a bit longer than load test duration
2. Run load test to generate around 100K sessions
3. Wait for timeout
4. 
**Expected behavior**
AM server will hang trying to housekeep the sessions and require tomcat restart to resolve it.
CTS will reach 100% cpu but restart is not required

**Screenshots**

**Server (please complete the following information):**
 - OS: Centos 7.6
 - Test tool: Jmeter 5
 - Version: Openam 14.4.2

**Additional context**

**Comment by vharseko** [comment]
please provide
```
jstack PID >> thread.dump
```

**Comment by vharseko** [comment]
please provide load test or jstack PID >> thread.dump
