### ISSUE TITLE
User Id Session filter on Top realm & Sub realm >> Sessions page not giving session details of logged in user

### ISSUE THREAD

**Issue by kumar1801** [OpenIdentityPlatform/OpenAM#220]
User Id filter on Top realm >> Sessions page not giving session details of Application level users

Steps to reproduce:

1) Logged in OpenAM 14.4.2 

2) Navigate to Top Realm >> sessions >> user id filter

3) Check for Filters on page >> filter with user :amadmin

Actual Result: Filter is giving result for user amadmin but will not give result for other application-level user.

Expected Result: Filter should work Properly with other realm level user.

Expected Result: Filter should work Properly
![2019-12-10_10h43_35](https://user-images.githubusercontent.com/11241656/70499389-0b052e80-1b3f-11ea-9f00-575cae01fc11.png)
![2019-12-10_10h45_58](https://user-images.githubusercontent.com/11241656/70499390-0b052e80-1b3f-11ea-8fc8-de6cc1739122.png)

**Comment by maximthomas** [comment]
@kumar1801 Hi, what do you mean - other realm level user? Could you describe how did you authenticate the account, which is not displayed in sessions filter?

**Comment by kumar1801** [comment]
@maximthomas 

Other realm means created sub-realm and user authenticated using sub-realm and I am finding his/her session with its UID.

With search, it's only giving session of amadmin user.

**Comment by maximthomas** [comment]
@kumar1801 

I can't reproduce the issue, created empty OpenAM installation, created sub-realm, created user with id `test`, authenticated the user, and as `amadmin` I can see this user session
<img width="1226" alt="screenshot-sessions" src="https://user-images.githubusercontent.com/7863782/71573673-30f67100-2af6-11ea-81a5-bdf3510e875f.png">

**Comment by kumar1801** [comment]
@maximthomas 
In Our case, we created sub-realm and user data store coming from our LDAP server.
We used our external LDAP server.
May you tried to create user on TOP-Level realm.

Attached image comparison between OpenAM12 and 14.

![2019-12-30](https://user-images.githubusercontent.com/11241656/71579335-24880d80-2b22-11ea-84d1-481cc0dd1fdd.png)

**Comment by maximthomas** [comment]
@kumar1801 
I created the user in sub-realm, but I can see it in top-level realm also, because they share same data source. I'll check your case again

**Comment by kumar1801** [comment]
@maximthomas 

Yes, You created sub-realm but may use the same datastore as in TOP-level realm.

In our case Top-Level realm data store pointing to OpenDJ
In sub-realm pointing our external LDAP server.

Top-Level realm - opnam-ldap.dvt.info.com:1389 [OpenDJ]
Sub-realm - ldap.dvt.info.com:389[User Data store]

Even in sub-realm, we are not using default attribute name mapping we have custom attributes in user data.

**Comment by maximthomas** [comment]
@kumar1801 I've just created pull request with issue fix, and you will able to find user session in his realm

**Comment by kumar1801** [comment]
@maximthomas 
Verified your changes and it is working fine.
Now user session available in search.
Thank you
