### ISSUE TITLE
Filter is not working in Authorization >> Policy sets and Resource Types

### ISSUE THREAD

**Issue by kumar1801** [OpenIdentityPlatform/OpenAM#222]
Filter is not working in Authorization >> Policy sets and Resource Types

Steps to reproduce:

1) Open Open AM 14 

2) Navigate to Top Realm >> Authorization >> Policy Sets , Resource Types

3) Check for Filters on page 

Actual Result: Filter is not working

Expected Result: Filter should work Properly

![2019-12-10_10h34_46](https://user-images.githubusercontent.com/11241656/70684788-5b11fb80-1ccd-11ea-95fe-b1d5fad0fed7.png)

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenAM/issues/655
