### ISSUE TITLE
authentication with external ldap module fails with authentication failed

### ISSUE THREAD

**Issue by spetix** [OpenIdentityPlatform/OpenAM#226]
I'm configuring an authentication module with an external LDAP source (it's another 14.4.2 openam server).

external source is pingable and reachable from openAM's machine on port 50389 (i've checked with ldapsearch)

i change LDAP "internal" in authentication chain, with LDAP "external" but user login fails (users are present on both systems and with the same set of passwords).

Only error i see in debug.out is:
LdapException: Unwilling to perform: Unable to process the simple bind request because it contained a bind DN but no password, which is forbidden by the server configuration..

Of course i've set the password field in module configuration and i've also tried to set it (after seeing this) with ssoadm update-auth-instance but no luck.

is extenal ldap module expected to work?

**Comment by maximthomas** [comment]
@spetix 
Hi, yes it works, I took demo ldap docker image https://hub.docker.com/r/kazhar/openldap-demo/, set up an external auth module with demo ldap service and authenticated users from this ldap.

**Comment by spetix** [comment]
ok so i can use an openDJ or another LDAP server but I can't use another openAM? correct? (just to make sure and tell or QA how to proceed with testing)
