### ISSUE TITLE
OpenAM-14.4.2.war intial config, cannot set amAdmin password

### ISSUE THREAD

**Issue by kenjohanson2** [OpenIdentityPlatform/OpenAM#232]
Trying to set up openam in Webapp (war) mode, the initial password setup prints 'Missing Password', and I cannot clicke 'next, even though I've entered >8 chars and complex sets (caps, numbers, symbols). This happens in any browser and on both the default config and custom config screens.

No errors appear in JS console, nor in Tomcat logs.

**Comment by maximthomas** [comment]
Hello, could you provide an error screenshot?

**Comment by kenjohanson2** [comment]
![image](https://user-images.githubusercontent.com/59965011/72533161-4e3b7700-383a-11ea-86d8-09fec2e827a9.png)

**Comment by kenjohanson2** [comment]
Hello @maximthomas.. curious if you were also able to reproduce this? Any suggestions how we can bypass it would be much appreciated..

**Comment by kenjohanson2** [comment]
My guess is the frontend is sending different password parameter names from what the backend expects. I was able to bypass the JS to just test, with a hack in function defaultAgentPasswordResponse and defaultAdminPasswordResponse, but then get a NPE:

amConfigurator:01/19/2020 04:56:19:167 PM CST: Thread[http-apr-0.0.0.0-80-exec-10,5,main]: TransactionId[93b65dec-1374-4ad2-ab9e-5f4792918e90-1]
ERROR: DefaultSummary.createDefaultConfig()
java.lang.NullPointerException
        at com.sun.identity.setup.ServicesDefaultValues.validatePassword(ServicesDefaultValues.java:335)
        at com.sun.identity.setup.ServicesDefaultValues.setServiceConfigValues(ServicesDefaultValues.java:126)
        at com.sun.identity.setup.AMSetupServlet.processRequest(AMSetupServlet.java:470)
        at com.sun.identity.config.DefaultSummary.createDefaultConfig(DefaultSummary.java:128)
...

**Comment by maximthomas** [comment]
I can't reproduce the issue, but on the screenshot I see enabled browser extensions. Could you disable them all and retry OpenAM install on a clean browser?

**Comment by maximthomas** [comment]
@kenjohanson2 have you tried to install on a clean browser?
