### ISSUE TITLE
Jato library incorrectly escapes some URLs

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM#246]
**Describe the bug**
This one looks like it should be easy to fix, but it's a nightmare under the hood. 
The non-XUI interface renders most of the "old-looking" tables using this little-known Jato library. Unfortunately it seems like it incorrectly escapes some URLs and the requests affected get rejected by recent versions of Tomcat (see https://stackoverflow.com/questions/41053653/tomcat-8-is-not-able-to-handle-get-request-with-in-query-parameters).

**To Reproduce**
1. Make sure you are using any of the affected Tomcat versions (7.0.73, 8.0.39, 8.5.7)
1. Go to Realms > Subjects > pick any user > Services tab
2. Click on any of the existing services
4. Tomcat returns an HTTP 400 error, because the URL is in the format http://login.domain.com:8080/openam/idm/EntityServices?EntityServices.tableTiledView[0].tblDataActionHref=dashboardService&jato.pageSession=AKztAA...Lip4 . The brackets are not escaped correctly.

**Expected behavior**
It should return the web page, if you escape the link manually it works fine.

**Diagnostics**
The old XUI pages are using the class import `com.iplanet.jato.taglib.html.HrefTag`, whose sources seem to be nowhere to be found. However by peeking inside the .class file, we find the following code:

```
protected void generateStartTagContent(NonSyncStringBuffer buffer) throws JspException {
    ContainerView parentContainer = getParentContainerView();
    View child = parentContainer.getChild(getName());
    checkChildType(child, CommandField.class);
    
    CommandField field = (CommandField)child;
    Object value = field.getValue();
    if (value == null) {
      value = getDefaultValue();
    }

    ViewBean viewBean = getParentViewBean();
    
    buffer.append("<a href=\"");
    appendHrefURL(buffer);
    
>>>
    buffer.append("?").append(field.getQualifiedName())**.append("=");
<<<

    if (value != null)
    {
      buffer.append(URLEncoder.encode(value.toString()));
    }
```

So close! The class escapes nearly all of the attributes, but forgets to escape the `field.getQualifiedName` return value, which causes the problem.

Now the real question is... how do we fix this mess?

- Hopefully the original library sources are out there and I just don't know where to find them, or
- We are referencing an old version of this library and maybe the fix is already out there in a newer version, or
- We could patch the existing .class file and reference our custom version of the binary dependency, or
- We could decompile the entire library and build a source dependency inside /commons

The thing is that these infrastructure/package management decisions are above my skill level. Do you have any idea about what would be the appropriate course of action here?

**Comment by lscorcia** [comment]
After some additional investigation, my initial finding was somewhat incorrect: the Services tab doesn't use the Jato library, but the com.sun.web.ui.taglib.html.CCHrefTag class in library cc-2008-08-08. The affected method is getURLString, which however has a very similar structure and the same error:

>>>    buffer.append("?").append(field.getQualifiedName()).append("=");

I have been trying to patch the binary .class file but I'm still having problems with Tomcat not loading the modified library.

**Comment by lscorcia** [comment]
Attached here [CCHrefTag.zip](https://github.com/OpenIdentityPlatform/OpenAM/files/4227478/CCHrefTag.zip) is the modified `CCHrefTag.class` file from `cc-2008-08-08.jar/com/sun/web/ui/taglib/html/` in order to fix this issue, but I need your help to apply this fix to the project.

The pom files reference package `cc-2008-08-08.jar` from https://oss.sonatype.org/#nexus-search;quick~com.sun.web.ui , but I have no idea about how to update that dependency. The appropriate action would probably be to deploy a new package version there, then tweaking the pom files to reference the new version of the compiled jar, but I don't know how to do that - I need your help here.

Some more info about how I generated the patched CCHrefTag class: I used https://github.com/Col-E/Recaf to explore the CCHrefTag.class file and add the `INVOKESTATIC` call to `java.net.URLEncoder.encode(string)`:

![immagine](https://user-images.githubusercontent.com/16761934/74878246-37230400-5367-11ea-8c85-7eee8f4229aa.png)

After exporting the modified .class file and checking that it actually decompiled to the intended code, I put it back into the jar file and replaced the library under the webapp `WEB-INF/lib` path (two gotchas: the build process renames it to `cc-14.4.3-SNAPSHOT.jar`, and make sure to maintain the correct permissions for the tomcat user). Restarted tomcat and the bug was gone!

**Comment by vharseko** [comment]
thanks for fix @lscorcia

**Comment by lscorcia** [comment]
You're welcome!

I think we still need to update the package on https://oss.sonatype.org/#nexus-search;quick~com.sun.web.ui - the build does not use the local file in `/extlib` but it loads the dependency from the package manager, at least on my machine...

**Comment by vharseko** [comment]
fixed https://oss.sonatype.org/#nexus-search;quick~org.openidentityplatform.external
use maven switch

**-U,--update-snapshots**                  
Forces a check for missing releases and updated snapshots on remote repositories

**Comment by lscorcia** [comment]
Uhm, no luck. I tried with the -U switch but the package still didn't change and doesn't include the fix.

**Comment by lscorcia** [comment]
Sorry to reopen this, but I am unable to get the fix in new builds of OpenAM, even when using the -U switch.

From sonatype I see the package has been modified on Feb 20th (but the package filename still says 20200218?):
![immagine](https://user-images.githubusercontent.com/16761934/75286195-5c58bc00-5818-11ea-8c6a-857c473917ca.png)

If I download the .jar using the link on the right, I see that the CCHrefTag class does not have a recent changed date:

![immagine](https://user-images.githubusercontent.com/16761934/75286232-75616d00-5818-11ea-99c5-b417ddb46844.png)

And if I decompile this class, the fix is not included:

![immagine](https://user-images.githubusercontent.com/16761934/75286329-a477de80-5818-11ea-8d5c-365cdc044181.png)

Do you have any idea why?

**Comment by lscorcia** [comment]
Yay! It works now! Thanks a lot @vharseko !
