### ISSUE TITLE
error in configuring openam using openam-configurator-tool

### ISSUE THREAD

**Issue by samene** [OpenIdentityPlatform/OpenAM#247]
Distribution built out of master branch 14.4.3-SNAPSHOT and opendj 4.4.4-SNAPSHOT [ **18-Feb-2020** ]

java -jar /usr/openam/ssoconfiguratortools/openam-configurator-tool-14.4.3-SNAPSHOT.jar --file /usr/openam/configurator.conf

Get below error

Attached install.log configurator.conf

`java -jar /usr/openam/ssoconfiguratortools/openam-configurator-tool-14.4.3-SNAPSHOT.jar --file /usr/openam/configurator.conf`

02/18/2020 09:46:18:629 AM UTC: Checking license acceptance...
02/18/2020 09:46:18:629 AM UTC: License terms accepted.
02/18/2020 09:46:18:639 AM UTC: Checking configuration directory /usr/openam/config.
02/18/2020 09:46:18:639 AM UTC: ...Success.
02/18/2020 09:46:18:642 AM UTC: Tag swapping schema files.
02/18/2020 09:46:18:659 AM UTC: ...Success.
02/18/2020 09:46:18:659 AM UTC: Loading Schema odsee_config_schema.ldif
02/18/2020 09:46:18:754 AM UTC: ...Success.
02/18/2020 09:46:18:754 AM UTC: Loading Schema odsee_config_index.ldif
02/18/2020 09:46:18:765 AM UTC: ...Success.
02/18/2020 09:46:18:765 AM UTC: Loading Schema cts-container.ldif
02/18/2020 09:46:18:791 AM UTC: ...Success.
02/18/2020 09:46:18:791 AM UTC: Loading Schema cts-add-schema.ldif
02/18/2020 09:46:18:858 AM UTC: ...Success.
02/18/2020 09:46:18:858 AM UTC: Loading Schema cts-add-multivalue.ldif
02/18/2020 09:46:18:933 AM UTC: ...Success.
02/18/2020 09:46:18:933 AM UTC: Loading Schema opendj_uma_audit.ldif
02/18/2020 09:46:18:953 AM UTC: ...Success.
02/18/2020 09:46:18:954 AM UTC: Loading Schema opendj_uma_resource_sets.ldif
02/18/2020 09:46:18:982 AM UTC: ...Success.
02/18/2020 09:46:18:982 AM UTC: Loading Schema opendj_uma_labels_schema.ldif
02/18/2020 09:46:19:031 AM UTC: ...Success.
02/18/2020 09:46:19:031 AM UTC: Loading Schema opendj_uma_resource_set_labels.ldif
02/18/2020 09:46:19:047 AM UTC: ...Success.
02/18/2020 09:46:19:047 AM UTC: Loading Schema opendj_uma_pending_requests.ldif
02/18/2020 09:46:19:061 AM UTC: ...Success.
02/18/2020 09:46:19:062 AM UTC: Reinitializing system properties.
amSecurity:02/18/2020 09:46:19:248 AM UTC: Thread[http-nio-8080-exec-3,5,main]: TransactionId[221de26e-4a9c-4f1f-87cb-592568595c3f-0]
Debug file can't be written : Failed to create debug directory Current Debug File : DebugFileImpl{debugDirectorynulldebugName='CoreSystem', fileCreationTime=01/01/1970 12:00:00:000 AM UTC}
amSecurity:02/18/2020 09:46:19:248 AM UTC: Thread[http-nio-8080-exec-3,5,main]: TransactionId[221de26e-4a9c-4f1f-87cb-592568595c3f-0]
ERROR: created internalAppSSOToken:Qm13aDlQYmtwZzR3aXdGRndLalFCZz09MTU4MjAxOTE3OTI0NQ==, authInitialized: false, SystemProperties.isServerMode(): true,  SystemProperties.get(AMADMIN_MODE): null
amSecurity:02/18/2020 09:46:19:254 AM UTC: Thread[http-nio-8080-exec-3,5,main]: TransactionId[221de26e-4a9c-4f1f-87cb-592568595c3f-0]
ERROR: created internalAppSSOToken:Ukl6dnFuZlFyam91bDlZN3dLalFCZz09MTU4MjAxOTE3OTE0NQ==, authInitialized: false, SystemProperties.isServerMode(): true,  SystemProperties.get(AMADMIN_MODE): null
02/18/2020 09:46:19:472 AM UTC: ...Done
02/18/2020 09:46:19:474 AM UTC: Registering service dashboardService.xml
02/18/2020 09:46:19:733 AM UTC: ...Success.
02/18/2020 09:46:19:734 AM UTC: Registering service amEntrySpecific.xml
02/18/2020 09:46:19:803 AM UTC: ...Success.
02/18/2020 09:46:19:803 AM UTC: Registering service amAuthConfig.xml
02/18/2020 09:46:20:054 AM UTC: ...Success.
02/18/2020 09:46:20:054 AM UTC: Registering service amAuthHTTPBasic.xml
02/18/2020 09:46:20:131 AM UTC: ...Success.
02/18/2020 09:46:20:131 AM UTC: Registering service amAdminConsole.xml
02/18/2020 09:46:20:235 AM UTC: ...Success.
02/18/2020 09:46:20:235 AM UTC: Registering service idRepoService.xml
02/18/2020 09:46:20:884 AM UTC: ...Success.
02/18/2020 09:46:20:884 AM UTC: Registering service amAuth.xml
02/18/2020 09:46:21:154 AM UTC: ...Success.
02/18/2020 09:46:21:154 AM UTC: Registering service amAuthAD.xml
02/18/2020 09:46:21:209 AM UTC: ...Success.
02/18/2020 09:46:21:209 AM UTC: Registering service amAuthAdaptive.xml
02/18/2020 09:46:21:303 AM UTC: ...Success.
02/18/2020 09:46:21:303 AM UTC: Registering service amAuthAnonymous.xml
02/18/2020 09:46:21:344 AM UTC: ...Success.
02/18/2020 09:46:21:344 AM UTC: Registering service amAuthCert.xml
02/18/2020 09:46:21:384 AM UTC: ...Success.
02/18/2020 09:46:21:384 AM UTC: Registering service amAuthDataStore.xml
02/18/2020 09:46:21:574 AM UTC: ...Success.
02/18/2020 09:46:21:574 AM UTC: Registering service amAuthPersistentCookie.xml
02/18/2020 09:46:21:625 AM UTC: ...Success.
02/18/2020 09:46:21:625 AM UTC: Registering service amAuthJDBC.xml
02/18/2020 09:46:21:659 AM UTC: ...Success.
02/18/2020 09:46:21:660 AM UTC: Registering service amAuthLDAP.xml
02/18/2020 09:46:21:796 AM UTC: ...Success.
02/18/2020 09:46:21:796 AM UTC: Registering service amAuthMSISDN.xml
02/18/2020 09:46:21:820 AM UTC: ...Success.
02/18/2020 09:46:21:820 AM UTC: Registering service amAuthMembership.xml
02/18/2020 09:46:21:846 AM UTC: ...Success.
02/18/2020 09:46:21:846 AM UTC: Registering service amAuthNT.xml
02/18/2020 09:46:21:868 AM UTC: ...Success.
02/18/2020 09:46:21:868 AM UTC: Registering service amAuthOAuth.xml
02/18/2020 09:46:21:900 AM UTC: ...Success.
02/18/2020 09:46:21:900 AM UTC: Registering service amAuthWindowsDesktopSSO.xml
02/18/2020 09:46:21:925 AM UTC: ...Success.
02/18/2020 09:46:21:925 AM UTC: Registering service amAuthOpenIdConnect.xml
02/18/2020 09:46:21:943 AM UTC: ...Success.
02/18/2020 09:46:21:944 AM UTC: Registering service amClientData.xml
02/18/2020 09:46:21:969 AM UTC: ...Success.
02/18/2020 09:46:21:969 AM UTC: Registering service amClientDetection.xml
02/18/2020 09:46:21:991 AM UTC: ...Success.
02/18/2020 09:46:21:991 AM UTC: Registering service amDelegation.xml
02/18/2020 09:46:22:515 AM UTC: ...Success.
02/18/2020 09:46:22:515 AM UTC: Registering service amFilteredRole.xml
02/18/2020 09:46:22:537 AM UTC: ...Success.
02/18/2020 09:46:22:538 AM UTC: Registering service amG11NSettings.xml
02/18/2020 09:46:22:552 AM UTC: ...Success.
02/18/2020 09:46:22:552 AM UTC: Registering service amLogging.xml
02/18/2020 09:46:22:595 AM UTC: ...Success.
02/18/2020 09:46:22:595 AM UTC: Registering service amNaming.xml
02/18/2020 09:46:22:630 AM UTC: ...Success.
02/18/2020 09:46:22:630 AM UTC: Registering service amPlatform.xml
02/18/2020 09:46:22:752 AM UTC: ...Success.
02/18/2020 09:46:22:752 AM UTC: Registering service amPolicy.xml
02/18/2020 09:46:23:515 AM UTC: ...Success.
02/18/2020 09:46:23:515 AM UTC: Registering service amPolicyConfig.xml
02/18/2020 09:46:23:598 AM UTC: ...Success.
02/18/2020 09:46:23:599 AM UTC: Registering service amRealmService.xml
02/18/2020 09:46:23:611 AM UTC: ...Success.
02/18/2020 09:46:23:611 AM UTC: Registering service amSession.xml
02/18/2020 09:46:23:701 AM UTC: ...Success.
02/18/2020 09:46:23:701 AM UTC: Registering service amWebAgent.xml
02/18/2020 09:46:23:727 AM UTC: ...Success.
02/18/2020 09:46:23:728 AM UTC: Registering service crestPolicyService.xml
02/18/2020 09:46:23:744 AM UTC: ...Success.
02/18/2020 09:46:23:745 AM UTC: Registering service amUser.xml
02/18/2020 09:46:23:769 AM UTC: ...Success.
02/18/2020 09:46:23:769 AM UTC: Registering service identityLocaleService.xml
02/18/2020 09:46:23:854 AM UTC: ...Success.
02/18/2020 09:46:23:854 AM UTC: Registering service amAgent70.xml
02/18/2020 09:46:23:878 AM UTC: ...Success.
02/18/2020 09:46:23:878 AM UTC: Registering service amPasswordReset.xml
02/18/2020 09:46:23:898 AM UTC: ...Success.
02/18/2020 09:46:23:898 AM UTC: Registering service amAuthRadius.xml
02/18/2020 09:46:23:922 AM UTC: ...Success.
02/18/2020 09:46:23:922 AM UTC: Registering service amAuthHOTP.xml
02/18/2020 09:46:24:038 AM UTC: ...Success.
02/18/2020 09:46:24:038 AM UTC: Registering service amMonitoring.xml
02/18/2020 09:46:24:052 AM UTC: ...Success.
02/18/2020 09:46:24:052 AM UTC: Registering service AgentService.xml
02/18/2020 09:46:24:272 AM UTC: ...Success.
02/18/2020 09:46:24:272 AM UTC: Registering service policyIndex.xml
02/18/2020 09:46:24:414 AM UTC: ...Success.
02/18/2020 09:46:24:415 AM UTC: Registering service entitlement.xml
02/18/2020 09:46:24:658 AM UTC: ...Success.
02/18/2020 09:46:24:658 AM UTC: Registering service openProvisioning.xml
02/18/2020 09:46:24:686 AM UTC: ...Success.
02/18/2020 09:46:24:686 AM UTC: Registering service banking.xml
02/18/2020 09:46:24:710 AM UTC: ...Success.
02/18/2020 09:46:24:710 AM UTC: Registering service CoreTokenConfig.xml
02/18/2020 09:46:24:740 AM UTC: ...Success.
02/18/2020 09:46:24:740 AM UTC: Registering service CoreTokenStore.xml
02/18/2020 09:46:24:804 AM UTC: ...Success.
02/18/2020 09:46:24:804 AM UTC: Registering service amAuthAuthenticatorOATH.xml
02/18/2020 09:46:24:832 AM UTC: ...Success.
02/18/2020 09:46:24:833 AM UTC: Registering service AuthenticatorOATH.xml
02/18/2020 09:46:24:850 AM UTC: ...Success.
02/18/2020 09:46:24:850 AM UTC: Registering service fmAuthFederation.xml
02/18/2020 09:46:24:955 AM UTC: ...Success.
02/18/2020 09:46:24:955 AM UTC: Registering service fmAuthSAE.xml
02/18/2020 09:46:25:097 AM UTC: ...Success.
02/18/2020 09:46:25:098 AM UTC: Registering service fmAuthnSvc.xml
02/18/2020 09:46:25:136 AM UTC: ...Success.
02/18/2020 09:46:25:136 AM UTC: Registering service fmDisco.xml
02/18/2020 09:46:25:179 AM UTC: ...Success.
02/18/2020 09:46:25:179 AM UTC: Registering service fmIDFF.xml
02/18/2020 09:46:25:215 AM UTC: ...Success.
02/18/2020 09:46:25:215 AM UTC: Registering service fmLibertyPersonalProfile.xml
02/18/2020 09:46:25:264 AM UTC: ...Success.
02/18/2020 09:46:25:264 AM UTC: Registering service fmCOTConfig.xml
02/18/2020 09:46:25:286 AM UTC: ...Success.
02/18/2020 09:46:25:286 AM UTC: Registering service fmSAML2.xml
02/18/2020 09:46:25:344 AM UTC: ...Success.
02/18/2020 09:46:25:344 AM UTC: Registering service fmSAML.xml
02/18/2020 09:46:25:379 AM UTC: ...Success.
02/18/2020 09:46:25:379 AM UTC: Registering service fmSOAPBinding.xml
02/18/2020 09:46:25:407 AM UTC: ...Success.
02/18/2020 09:46:25:407 AM UTC: Registering service fmSAML2SOAPBinding.xml
02/18/2020 09:46:25:418 AM UTC: ...Success.
02/18/2020 09:46:25:418 AM UTC: Registering service fmWSFederation.xml
02/18/2020 09:46:25:441 AM UTC: ...Success.
02/18/2020 09:46:25:441 AM UTC: Registering service fmMultiProtocol.xml
02/18/2020 09:46:25:467 AM UTC: ...Success.
02/18/2020 09:46:25:467 AM UTC: Registering service famSTS.xml
02/18/2020 09:46:25:489 AM UTC: ...Success.
02/18/2020 09:46:25:489 AM UTC: Registering service famFederationCommon.xml
02/18/2020 09:46:25:506 AM UTC: ...Success.
02/18/2020 09:46:25:507 AM UTC: Registering service famIDFFConfig.xml
02/18/2020 09:46:25:520 AM UTC: ...Success.
02/18/2020 09:46:25:520 AM UTC: Registering service famSAML2Config.xml
02/18/2020 09:46:25:552 AM UTC: ...Success.
02/18/2020 09:46:25:552 AM UTC: Registering service famWSSAuthService.xml
02/18/2020 09:46:25:664 AM UTC: ...Success.
02/18/2020 09:46:25:664 AM UTC: Registering service OAuth2Provider.xml
02/18/2020 09:46:25:703 AM UTC: ...Success.
02/18/2020 09:46:25:703 AM UTC: Registering service UmaProvider.xml
02/18/2020 09:46:25:727 AM UTC: ...Success.
02/18/2020 09:46:25:727 AM UTC: Registering service MailServer.xml
02/18/2020 09:46:25:749 AM UTC: ...Success.
02/18/2020 09:46:25:749 AM UTC: Registering service RestSecurity.xml
02/18/2020 09:46:25:768 AM UTC: ...Success.
02/18/2020 09:46:25:768 AM UTC: Registering service amAuthScripted.xml
02/18/2020 09:46:25:795 AM UTC: ...Success.
02/18/2020 09:46:25:796 AM UTC: Registering service amAuthDeviceIdMatch.xml
02/18/2020 09:46:25:818 AM UTC: ...Success.
02/18/2020 09:46:25:818 AM UTC: Registering service amAuthDeviceIdSave.xml
02/18/2020 09:46:25:835 AM UTC: ...Success.
02/18/2020 09:46:25:835 AM UTC: Registering service restSTS.xml
02/18/2020 09:46:25:868 AM UTC: ...Success.
02/18/2020 09:46:25:868 AM UTC: Registering service soapSTS.xml
02/18/2020 09:46:25:906 AM UTC: ...Success.
02/18/2020 09:46:25:906 AM UTC: Registering service validationService.xml
02/18/2020 09:46:25:929 AM UTC: ...Success.
02/18/2020 09:46:25:929 AM UTC: Registering service RestApis.xml
02/18/2020 09:46:25:963 AM UTC: ...Success.
02/18/2020 09:46:25:963 AM UTC: Registering service socialAuthN.xml
02/18/2020 09:46:26:000 AM UTC: ...Success.
02/18/2020 09:46:26:000 AM UTC: Registering service amBaseURL.xml
02/18/2020 09:46:26:031 AM UTC: ...Success.
02/18/2020 09:46:26:031 AM UTC: Registering service scripting.xml
02/18/2020 09:46:26:369 AM UTC: ...Success.
02/18/2020 09:46:26:369 AM UTC: Registering service amAuthOATH.xml
02/18/2020 09:46:26:608 AM UTC: ...Success.
02/18/2020 09:46:26:608 AM UTC: Registering service amAuthSAML2.xml
02/18/2020 09:46:26:673 AM UTC: ...Success.
02/18/2020 09:46:26:673 AM UTC: Registering service audit.xml
02/18/2020 09:46:26:967 AM UTC: ...Success.
02/18/2020 09:46:26:967 AM UTC: Registering service RadiusServerService.xml
02/18/2020 09:46:27:014 AM UTC: ...Success.
02/18/2020 09:46:27:015 AM UTC: Registering service amSessionPropertyWhitelist.xml
02/18/2020 09:46:27:064 AM UTC: ...Success.
02/18/2020 09:46:27:064 AM UTC: Registering service selfService.xml
02/18/2020 09:46:27:111 AM UTC: ...Success.
02/18/2020 09:46:27:111 AM UTC: Registering service amPushNotification.xml
02/18/2020 09:46:27:135 AM UTC: ...Success.
02/18/2020 09:46:27:135 AM UTC: Registering service amAuthAuthenticatorPush.xml
02/18/2020 09:46:27:184 AM UTC: ...Success.
02/18/2020 09:46:27:185 AM UTC: Registering service AuthenticatorPush.xml
02/18/2020 09:46:27:202 AM UTC: ...Success.
02/18/2020 09:46:27:202 AM UTC: Registering service amAuthAuthenticatorPushRegistration.xml
02/18/2020 09:46:27:218 AM UTC: ...Success.
02/18/2020 09:46:27:218 AM UTC: Registering service amAuthAmster.xml
02/18/2020 09:46:27:289 AM UTC: ...Success.
02/18/2020 09:46:27:289 AM UTC: Registering service amAuthReCaptcha.xml
02/18/2020 09:46:27:311 AM UTC: ...Success.
02/18/2020 09:46:27:311 AM UTC: Registering service amAuthSecurID.xml
02/18/2020 09:46:27:335 AM UTC: ...Success.
02/18/2020 09:46:27:335 AM UTC: Registering service amAuthWebAuthnRegistration.xml
02/18/2020 09:46:27:357 AM UTC: ...Success.
02/18/2020 09:46:27:357 AM UTC: Registering service amAuthWebAuthnAuthentication.xml
02/18/2020 09:46:27:380 AM UTC: ...Success.
02/18/2020 09:46:27:381 AM UTC: Configuring system.
02/18/2020 09:46:29:421 AM UTC: ...Done
02/18/2020 09:46:29:422 AM UTC: Configuring server instance.
02/18/2020 09:46:29:471 AM UTC: ...Done
02/18/2020 09:46:29:647 AM UTC: Loading Schema /usr/openam/config/opendj_user_schema.ldif
02/18/2020 09:46:29:759 AM UTC: ...Success.
02/18/2020 09:46:29:759 AM UTC: Loading Schema /usr/openam/config/opendj_userinit.ldif
02/18/2020 09:46:29:784 AM UTC: ...Success.
02/18/2020 09:46:29:784 AM UTC: Loading Schema /usr/openam/config/opendj_user_index.ldif
02/18/2020 09:46:29:841 AM UTC: ...Success.
02/18/2020 09:46:29:842 AM UTC: Loading Schema /usr/openam/config/opendj_dashboard.ldif
02/18/2020 09:46:29:894 AM UTC: ...Success.
02/18/2020 09:46:29:894 AM UTC: Loading Schema /usr/openam/config/opendj_deviceprint.ldif
02/18/2020 09:46:29:936 AM UTC: ...Success.
02/18/2020 09:46:29:936 AM UTC: Loading Schema /usr/openam/config/opendj_kba.ldif
02/18/2020 09:46:29:973 AM UTC: ...Success.
02/18/2020 09:46:29:974 AM UTC: Loading Schema /usr/openam/config/opendj_oathdevices.ldif
02/18/2020 09:46:30:005 AM UTC: ...Success.
02/18/2020 09:46:30:005 AM UTC: Loading Schema /usr/openam/config/opendj_pushdevices.ldif
02/18/2020 09:46:30:056 AM UTC: ...Success.
com.sun.identity.setup.ConfiguratorException: Unable to initialize AuthD, refer to install.log under /usr/openam/config for more information.
	at com.sun.identity.setup.AMSetupServlet.processRequest(AMSetupServlet.java:585)
	at com.sun.identity.setup.AMSetupServlet.doPost(AMSetupServlet.java:443)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.forgerock.openam.validation.ResponseValidationFilter.doFilter(ResponseValidationFilter.java:44)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.forgerock.openam.headers.SetHeadersFilter.doFilter(SetHeadersFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.sun.identity.setup.AMSetupFilter.doFilter(AMSetupFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.forgerock.openam.audit.context.AuditContextFilter.doFilter(AuditContextFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Configuration Failed.  The server returned error code :500

**Comment by samene** [comment]
[logs.zip](https://github.com/OpenIdentityPlatform/OpenAM/files/4218565/logs.zip)

**Comment by vharseko** [comment]
please check pull https://github.com/OpenIdentityPlatform/OpenAM/commit/1448d4fab2aee4ac9c0f79da6b7b33b9e15d9323
