### ISSUE TITLE
Default configuration is stuck

### ISSUE THREAD

**Issue by kmoussa** [OpenIdentityPlatform/OpenAM#250]
**Describe the bug**
I followed the steps in the wiki to deploy OpenAM on kubernetes but I'm using AKS instead of plain vanilla kubernetes.
everything goes smooth till I try to configure the openam using the default configuration, it generates the following error:
/usr/openam/config/opends/opendj.zip (No such file or directory), refer to install.log under /usr/openam/config for more information.

it seems that there is a write permission issue on the mounted persistance volume

**To Reproduce**
follow these steps 
https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-To-Run-OpenAM-in-Kubernetes

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Brave
 - Version 1.13.115

**Comment by maximthomas** [comment]
@kmoussa 
Has the VolumeClaim created for OpenAM created? Does OpenAM pod have read-write access rights?
please attach install.log from /usr/openam/config from OpenAM pod

**Comment by kmoussa** [comment]
@maximthomas , yes , it is created and it has RWO access rights, the install.log isn't there because the Pod is not able to write on /usr/openam/config!!

**Comment by maximthomas** [comment]
@kmoussa 
It should be able, because in /usr/openam/config should be all OpenAM configuraion files, including OpenDJ

**Comment by kmoussa** [comment]
@maximthomas , well this is not the case, this was a newly created cluster, I only had Kong api gateway installed on it, I'll try to set this up again on a brand new one and let you know.

**Comment by maximthomas** [comment]
@kmoussa hi, are you still facing the issue?

**Comment by kmoussa** [comment]
@maximthomas yes , it's still giving me the same error message.

**Comment by maximthomas** [comment]
@kmoussa try this commit aa47ed490c6b4fece4fe321e069822dcac61a03e

**Comment by kmoussa** [comment]
@maximthomas , thanks will try it and let you know.
