### ISSUE TITLE
Build date in footer isn't current

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM#251]
**Describe the bug**
I know it's just a dumb thing, but is the build date in the footer supposed to change in local builds?

In my local builds is stuck at:
![immagine](https://user-images.githubusercontent.com/16761934/74880123-dac1e380-536a-11ea-9801-65f8258997ab.png)

Maybe I am missing something in my build command?

**To Reproduce**
1. Build locally according to the instructions in file readme.md (btw, it needs to be updated: forgerock-parent -> commons)
    - mvn -DskipTests -Dmaven.javadoc.skip=true install -f OpenAM/OpenDJ/forgerock-parent
    - mvn -DskipTests -Dmaven.javadoc.skip=true install -f OpenAM/OpenDJ
    - mvn install -f OpenAM

2. Deploy to tomcat
3. Login as amadmin

**Expected behavior**
It would make sense if it had the build date (and maybe the local git commit ref?) in there.

**Comment by vharseko** [comment]
this timestamp from config DB (ldap)
 timestamp changes when the configuration is updated in DB

**Comment by lscorcia** [comment]
Oh, ok! I didn't know that!
Thanks for the explanation!
