### ISSUE TITLE
Disable Audit log

### ISSUE THREAD

**Issue by tupyy** [OpenIdentityPlatform/OpenAM#255]
Hello,

I'm using OpenAM 14.0.0 and I have a ton of these entries in the catalina.out file. 

```
11:39:17.061 [Worker Thread 1] DEBUG org.forgerock.audit.AuditServiceImpl - Audit create id 68134d0e-2fe2-46fc-b735-c521c764368c-8
11:39:17.061 [Worker Thread 1] DEBUG org.forgerock.audit.AuditServiceImpl - Cascading the event of topic ldap-access to the handlers : [org.forgerock.audit.handlers.json.JsonAuditEventHandler@68b938b0]
```

I want to disable this audit because it is impossible to watch the `catalina.log` due the high volume of these logs.
Could you point me to a solution please?

Thanks a log

**Comment by maximthomas** [comment]
@tupyy 
By default OpenAM does not log these events, seems you should look at  Configure > Global Services > Audit Logging

**Comment by tupyy** [comment]
@maximthomas 
I did. Audit Logging is disabled but I still have the log entries.

**Comment by vharseko** [comment]
@tupyy please attach catalina.out catalina.log from "re-start" process to first "DEBUG org.forgerock.audit.AuditServiceImpl"  event

**Comment by vharseko** [comment]
please upgrade to latest version https://github.com/OpenIdentityPlatform/OpenAM/releases

**Comment by tupyy** [comment]
@vharseko upgraded to latest version. I have the same issue.
From what I can see in the tomcat log there the service which generate these logs is:
```
11:39:10.580 [main] DEBUG org.forgerock.audit.AuditServiceBuilder - Registered []
 70 11:39:10.881 [main] DEBUG org.forgerock.audit.AuditServiceBuilder - Registering handler 'Json File-Based Access Logger' for [ldap-access] topics
```

I've attached the catalina.out.
[catalina.log](https://github.com/OpenIdentityPlatform/OpenAM/files/4260544/catalina.log)

**Comment by vharseko** [comment]
please check version https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/14.4.2  instead of version 14.3.1

**Comment by tupyy** [comment]
The version is 14.4.2.
![Screenshot_20200227_105253](https://user-images.githubusercontent.com/20856208/75432972-895bba80-594f-11ea-8bf8-4250c34bf2d2.png)

**Comment by vharseko** [comment]
please check attached catalina.out: openam-slf4j-**14.3.1**.jar
```
SLF4J: Found binding in [jar:file:/opt/workspace/openam/apache-tomcat-9.0.17/webapps/openam/WEB-INF/lib/openam-slf4j-14.3.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]

```

**Comment by tupyy** [comment]
hello,
@vharseko 
```
[xx@xxxx webapps]$ pwd
/opt/workspace/openam/apache-tomcat-9.0.17/webapps
[xx@xxx webapps]$ find . -name "*slf*"
./openam/WEB-INF/lib/jul-to-slf4j-1.7.25.jar
./openam/WEB-INF/lib/log4j-over-slf4j-1.7.7.jar
./openam/WEB-INF/lib/i18n-slf4j-1.4.2.jar
./openam/WEB-INF/lib/jcl-over-slf4j-1.7.25.jar
./openam/WEB-INF/lib/slf4j-api-1.7.25.jar
./openam/WEB-INF/lib/**openam-slf4j-14.4.2.jar**
./openam/WEB-INF/lib/org.restlet.ext.slf4j-2.3.4.jar
```
I cannot find any `openam-slf4j-14.3.1.jar` in any tomcat folder.

**Comment by vharseko** [comment]
please repeat catalina.log

**Comment by tupyy** [comment]
Sorry I don't understand. 
what do you mean?

**Comment by vharseko** [comment]
please check https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/14.5.1
