### ISSUE TITLE
Error starting latest sources

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM#259]
**Describe the bug**
I have built OpenAM from the latest sources (e1bd8f1) and it does not start anymore - I get the attached errors during Tomcat startup. Other log files seem empty (there are no recent entries neither in openam/debug nor in openam/opends/logs).

[catalina.log](https://github.com/OpenIdentityPlatform/OpenAM/files/4258227/catalina.log)

**Additional context**
Deployment on my dev VM which already had a configuration store initialized.

**Comment by maximthomas** [comment]
@lscorcia seems configuration store is not available from your OpenAM instance. To make OpenAM log more verbose please add `-Dcom.iplanet.services.debug.level=message` to Tomcat's `setenv.sh` file. Hope this will help to figure out the cause of the problem

**Comment by lscorcia** [comment]
I have restored a previous snapshot of the VM and rebuilt and redeployed - this time it warned me at startup that it would have updated the opendj config database and then started. I guess my machine was somehow borked.
Thanks for your help, the Tomcat switch you mentioned will turn out useful in the future!
