### ISSUE TITLE
XUI Login with LDAP-only chain fails

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM#260]
**Describe the bug**
When using a chain containing only the LDAP module, logins using XUI fail with error `403 - Forbidden Request Error`. The actual login process works, but the XUI is not able to get the username from the `getSessionInfo` endpoint and therefore does not proceed to the user console.
The problem is not present when logging with the default DataStore module, or when XUI is disabled.

**To Reproduce**
1. Create a LDAP module pointing to some LDAP server (embedded OpenDJ is ok)
2. Create a chain called `ldapService`, with the LDAP module as required
3. Visit http://login.domain.com:8080/openam/XUI/?service=ldapService#login
4. Try to login with a LDAP user (if using embedded OpenDJ, use user `demo`, password `changeit`) 
5. See error

**Expected behavior**
User should be able to login correctly.

**Diagnostics**
The problem is caused by an incorrect assumption in the `getSessionInfo` endpoint - it is retrieving the user name by calling the `getName` method on the user principal, but this only works for users which are authenticated on the internal DataStore. The correct, generic way to retrieve the username is to get the `sun.am.UniversalIdentifier` property from the `ssoToken`.
I will provide a pull request soon.

**Comment by bthalmayr** [comment]
The actual issue is that XUI calls the identity endpoint which is not needed at all during authentication.
