### ISSUE TITLE
Issue on master version (14.4.3-SNAPSHOT)

### ISSUE THREAD

**Issue by alezucchelli93** [OpenIdentityPlatform/OpenAM#264]
I clone the master and build it.
I update my openam from 14.4.2 to 14.4.3-SNAPSHOT (after the fix issue #258)
The upgrade is OK,but after the upgrade my openam has change the url:
from
devops-openam.int.softsolutions.it:8080/openam
to
devops-openam:8080/openam

There is a method to fix it?
Thanks

Regards

**Comment by vharseko** [comment]
check  Configuration > Servers and Sites config
