### ISSUE TITLE
OpenAM 14.4.2 to 14.5.1 upgrade fails at upgrading opends

### ISSUE THREAD

**Issue by samene** [OpenIdentityPlatform/OpenAM#265]
System running OpenAM 14.4.2 with embedded OpenDJ 4.4.4 in Apache Tomcat/8.5.34

After replacing the war file with openam 14.5.1 release and starting tomcat server seeing error in logs (attached)

The upgrade file mentioned in catalina logs - /home/tomcat/openam/opends/logs/upgrade.log is empty.

**Comment by samene** [comment]
[openam_upgrade_bug.zip](https://github.com/OpenIdentityPlatform/OpenAM/files/4348182/openam_upgrade_bug.zip)

**Comment by samene** [comment]
any updates?

**Comment by vharseko** [comment]
please check https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/14.7.3
