### ISSUE TITLE
Persistent Cookie checkbox name parameter

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM#269]
Hi, I'm trying to understand how to correctly use the "Check box name" parameter in the Persistent Cookie module. According to the field help text, this is the name attribute of a custom `input type=checkbox` tag that should let the user enable the persistent cookie feature from the login page.
I tried customizing my login UI to add such a checkbox but this didn't work, because the XUI does not pass custom form attributes to the `/authenticate` endpoint, rather it sets "requirements" for each callback expected by the specific authentication module.

Before trying to modify the requirements for the LDAP/DataStore module, which could take a long time, I'm thinking that maybe I am missing something? Is there some other way to supply this parameter via the XUI, or is it designed to be used in completely-custom login UIs?

Thanks for your help!

**Comment by maximthomas** [comment]
@lscorcia 
Hi, this functionality can only be used in classic or custom OpenAM UI and does not work in default XUI
