### ISSUE TITLE
Self Service ReCaptcha is not centered in page

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM#270]
**Describe the bug**
A small cosmetic issue - the ReCaptcha control is off-center in User Registration, Forgotten Password and Forgotten Username self service pages.

**To Reproduce**
1. Configure the ReCaptcha keys in Services > User Self Service > General Configuration
2. Enable Captcha in User Registration, Forgotten Password and Forgotten Username tabs
3. Logout 
4. Try User registration:
![immagine](https://user-images.githubusercontent.com/16761934/77592657-efa60f80-6ef2-11ea-8b8f-8462ee65f3ea.png)
5. Try Forgotten password:
![immagine](https://user-images.githubusercontent.com/16761934/77592599-c9806f80-6ef2-11ea-83e2-ad45af3b531c.png)
6. Try Forgotten username:
![immagine](https://user-images.githubusercontent.com/16761934/77592637-e1f08a00-6ef2-11ea-9c33-31beb889791b.png)

**Expected behavior**
The captcha should be center aligned like the other controls.

**Additional context**
The issue is due to a small CSS error, I will provide a pull request as soon as I can.

**Comment by lscorcia** [comment]
Here we are! The fix requires both pull request OpenIdentityPlatform/commons#17 to remove the hardcoded styling from the ReCaptcha self service templates and #271 in order to readd the correct style rule directly in the `openam.less` style sheet. This also means updating the submodules.

**Comment by maximthomas** [comment]
@lscorcia thanks!
