### ISSUE TITLE
ReCaptcha module proxy support

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM#273]
**Describe the bug**
When using the ReCaptcha module, the server has to access Google servers to validate the captcha. Unfortunately the `HttpClient` used by OpenAM is not configured to use proxy servers specified as Tomcat variables.

**To Reproduce**
1. In your enviroment, only allow access to the Internet via a proxy server
2. Set the `JAVA_OPTS` in the `setenv.sh` file as follows:
`JAVA_OPTS="$JAVAOPTS -Dhttps.proxyHost=<your_proxy_host> -Dhttps.proxyPort=<your_proxy_port> -Dhttps.nonProxyHosts=\"localhost|127.0.0.1|<whatever>\" -Dhttp.proxyHost=<your_proxy_host> -Dhttp.proxyPort=<your_proxy_port> -Dhttp.nonProxyHosts=\"localhost|127.0.0.1|<whatever>\""`
3. Configure a ReCaptcha module for login or user self service
4. Try to complete a ReCaptcha-enabled flow, you will get an Internal Server Error

**Expected behavior**
The ReCaptcha module should be able to access Google servers via the configured proxy.

**Additional context**
The fix should be easy, I will provide a pull request as soon as possible.

**Comment by lscorcia** [comment]
The fix requires both pull request OpenIdentityPlatform/commons#18 and #274 , so we need to update submodules.

**Comment by lscorcia** [comment]
Thanks! Could you please update submodules?

**Comment by vharseko** [comment]
done
