### ISSUE TITLE
How to Disable Audit log in OpenAM

### ISSUE THREAD

**Issue by ranjan1990** [OpenIdentityPlatform/OpenAM#277]
Hello,
I am using openAM dockerised version 14.4.1 Build b71849cdac (2019-July-29 22:10). And I have a ton of below entries in logs generated using command (docker log <openAm_containerId>). Not sure how to disable that.

[Worker Thread 5] DEBUG org.forgerock.audit.AuditServiceImpl - Audit create id 698a6ef1-35e3-4fb8-952b-e604c6f4c37f-8873

[Worker Thread 5] DEBUG org.forgerock.audit.AuditServiceImpl - Cascading the event of topic ldap-access to the handlers : [org.forgerock.audit.handlers.json.JsonAuditEventHandler@1578599f]

[Worker Thread 9] DEBUG org.forgerock.audit.AuditServiceImpl - Audit create id 698a6ef1-35e3-4fb8-952b-e604c6f4c37f-8875

[Worker Thread 9] DEBUG org.forgerock.audit.AuditServiceImpl - Cascading the event of topic ldap-access to the handlers : [org.forgerock.audit.handlers.json.JsonAuditEventHandler@1578599f]

[Worker Thread 14] DEBUG org.forgerock.audit.AuditServiceImpl - Audit create id 698a6ef1-35e3-4fb8-952b-e604c6f4c37f-8877

[Worker Thread 14] DEBUG org.forgerock.audit.AuditServiceImpl - Cascading the event of topic ldap-access to the handlers : [org.forgerock.audit.handlers.json.

Steps taken to solve it:
Disabled  Audit logging (Configure > Global Services > Audit Logging)

Tried multiple ways but still facing the same issue. Any solution highly appreciable. 

A Query here,  What is correct path for logs generated in dockerised openAM  in Linux, apart from docker logs command.

**Comment by vharseko** [comment]
please check https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/14.5.1

**Comment by vharseko** [comment]
fixed from 14.5.1
