### ISSUE TITLE
XUI is not using theme for realms with uppercase

### ISSUE THREAD

**Issue by spetix** [OpenIdentityPlatform/OpenAM#285]
It seems not possible to associate a realm uppercase (i.e. MYREALM) to a theme. Logo is not shown in XUI. I've tried with OpenAM 14.5.1

**How to reproduce**
- Create a realm with uppercase name, i.e (MYREALM).
- Add a theme for that realm, with logo and so on.
- go to login page for that realm, logo is not shown.

**Expected behavior**
when landing to login page for that specific realm i expect to see its logo. Everything works properly if realm is created with lowercase (myrealm)

**Desktop (please complete the following information):**
 - OS: Windows/Linux
 - Browser: Chrome, Firefox

**Comment by vharseko** [comment]
cannot reproduce problem
