### ISSUE TITLE
Forgerock Maven site is down

### ISSUE THREAD

**Issue by hailasjad** [OpenIdentityPlatform/OpenAM#290]
the maven site for forgerock build is down 
https://maven.forgerock.org/repo

**Comment by maximthomas** [comment]
@hailasjad OpenAM does not use forgerock repo whild build the project. If you have a problem while building, please attach build log.

**Comment by vharseko** [comment]
OpenAM does not use forgerock repo whild build the project. If you have a problem while building, please attach build log.
