### ISSUE TITLE
Error in login page after a logout for session timeout  on firefox

### ISSUE THREAD

**Issue by spetix** [OpenIdentityPlatform/OpenAM#296]
**Describe the bug**
When session expires, providing credentials again leads to an error and login button is grayed. If refresh is performed everthing works correctly

**To Reproduce**
1. Login
2. Open a page of your application (we don't use J2EE security, only agent and policies).
3. Let the session expire for session timeout
4. Wait a few more minutes and enter username and password
5. Error banner appears on XUI top and login button is grayed and it's no longer possible to press it

Chrome seems not affected (or it seems way more difficult to reproduce the issue - our QA reported they've seen it on Chrome as well but i can't reproduce it). 

Firefox: if re-login is attempted immediately after timeout everything works properly. If we wait some minute error occurs/

**Expected behavior**
We expect user to login and then a redirection to the goto page specified. When this happens in firefox the following error is present in Console
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Screenshots**
![firefox_issue_w_openam](https://user-images.githubusercontent.com/10819778/87295051-eb831980-c504-11ea-9927-b38aa5cb7e94.png)

**Desktop (please complete the following information):**
 - OS: Linux/Windows (not tested on OS-X)
 - Firefox 78.0.2 and other versions as well

**Comment by maximthomas** [comment]
Hi @spetix, is the issues still relevant? If yes, please reopen the issue
