### ISSUE TITLE
Session Upgrade fails since user is different than original authenticated user

### ISSUE THREAD

**Issue by kumar1801** [OpenIdentityPlatform/OpenAM#297]
Exception in Authentication Log

> amAuth:07/07/2020 01:56:10:055 PM EDT: Thread[http-nio-8080-exec-219,5,main]: TransactionId[749576da-c38a-450d-9881-b453be157bf9-15139263]
normalized special dn is :cn=amservice-urlaccessagent,ou=dsame users,dc=sso,o=sso.test.com
amAuth:07/07/2020 01:56:10:055 PM EDT: Thread[http-nio-8080-exec-219,5,main]: TransactionId[749576da-c38a-450d-9881-b453be157bf9-15139263]
is Special User :false
amAuth:07/07/2020 01:56:10:056 PM EDT: Thread[http-nio-8080-exec-219,5,main]: TransactionId[749576da-c38a-450d-9881-b453be157bf9-15139263]
activate before isSessionUpgrade=true forceAuth=false getSessionActivator=DefaultSessionActivator oldSessionReference=AQIC5wM2LY4SfcxkR8QK_mItMpLRpGbUHy0S_WP9DCXrP
0o.*AAJTSQACMDIAAlNLABM1MjM1ODI5MjU4ODk4Nzg4NTc4AAJTMQACMDQ.* getOldSession=null sessionReference=AQIC5wM2LY4SfcwR2XNgpV5SIAo2fwtaTCXd2Zn4LuplFcw.*AAJTSQACMDIAAlNL
ABQtMzc1NzgwNzI5MjM2MDYwMDcyNwACUzEAAjA0* getSession=com.iplanet.dpro.session.service.InternalSession@67d63d9 sid=AQIC5wM2LY4SfcwR2XNgpV5SIAo2fwtaTCXd2Zn4LuplFcw.*AAJTSQACMDIAAlNLABQtMzc1NzgwNzI5MjM2MDYwMDcyNwACUzEAAjA0* finalSessionId=AQIC5wM2LY4SfcwR2XNgpV5SIAo2fwtaTCXd2Zn4LuplFcw.*AAJTSQACMDIAAlNLABQtMzc1NzgwNzI5MjM2MDYwMDcyNwACUzEAAjA0*
amAuth:07/07/2020 01:56:10:056 PM EDT: Thread[http-nio-8080-exec-219,5,main]: TransactionId[749576da-c38a-450d-9881-b453be157bf9-15139263]
LoginState getSession = com.iplanet.dpro.session.service.InternalSession@67d63d9 sid=AQIC5wM2LY4SfcwR2XNgpV5SIAo2fwtaTCXd2Zn4LuplFcw.*AAJTSQACMDIAAlNLABQtMzc1NzgwNzI5MjM2MDYwMDcyNwACUzEAAjA0*
request token = 1221887@xyz.abc.com
amAuth:07/07/2020 01:56:10:056 PM EDT: Thread[http-nio-8080-exec-219,5,main]: TransactionId[749576da-c38a-450d-9881-b453be157bf9-15139263]
LoginState.setSessionProperties() userDN is: id=1221887@xyz.abc.com,ou=user,o=xyz.abc.com,ou=services,dc=sso,o=sso.test.com
amAuth:07/07/2020 01:56:10:056 PM EDT: Thread[http-nio-8080-exec-219,5,main]: TransactionId[749576da-c38a-450d-9881-b453be157bf9-15139263]
LoginState.setSessionProperties() oldUserDN is: null
amAuth:07/07/2020 01:56:10:057 PM EDT: Thread[http-nio-8080-exec-219,5,main]: TransactionId[749576da-c38a-450d-9881-b453be157bf9-15139263]
LoginState.setSessionProperties() sessionUpgrade is: true
amAuth:07/07/2020 01:56:10:057 PM EDT: Thread[http-nio-8080-exec-219,5,main]: TransactionId[749576da-c38a-450d-9881-b453be157bf9-15139263]
LoginState.setSessionProperties()Resetting session upgrade to false since oldAMIdentity and newAMIdentity doesn't match
amAuth:07/07/2020 01:56:10:058 PM EDT: Thread[http-nio-8080-exec-219,5,main]: TransactionId[749576da-c38a-450d-9881-b453be157bf9-15139263]
ERROR: Error setting session properties:
com.sun.identity.authentication.service.AuthException: Session Upgrade fails since user is different than original authenticated user
        at com.sun.identity.authentication.service.LoginState.setSessionProperties(LoginState.java:1253)
        at com.sun.identity.authentication.service.DefaultSessionActivator.activateSession(DefaultSessionActivator.java:66)
        at com.sun.identity.authentication.service.LoginState.activateSession(LoginState.java:1107)
        at com.sun.identity.authentication.service.AMLoginContext.runLogin(AMLoginContext.java:639)
        at com.sun.identity.authentication.server.AuthContextLocal.submitRequirements(AuthContextLocal.java:586)

Federation failed with the exception

> SPACSUtils.processResponse: process: attrMap = {uid=[1221887], ssoattribute_countrycode=[US], externalgivenname=[Amy], externalsurname=[Chen], email=[Amy.Chen@xyz.com]}
libSAML2:07/07/2020 01:56:09:595 PM EDT: Thread[http-nio-8080-exec-219,5,main]: TransactionId[749576da-c38a-450d-9881-b453be157bf9-15139263]
SPACSUtils.processResponse: userName : id=1221887@xyz.abc.com,ou=user,o=xyz.abc.com,ou=services,dc=sso,o=sso.test.com
libSAML2:07/07/2020 01:56:10:061 PM EDT: Thread[http-nio-8080-exec-219,5,main]: TransactionId[749576da-c38a-450d-9881-b453be157bf9-15139263]
SPACSUtils.processResponse : error code=-1
com.sun.identity.plugin.session.SessionException: Login Failed
Session Upgrade fails since user is different than original authenticated user

This happens when AuthRequest is generated from one server, Response is processed on another server. Session is created with empty DN (somehow, information about the principal is not transferred from one server to another).
Then Federation is initiated again from the second server and get processed on the second server. SSO finds old session, tried to get principal from the old session and finds it null. Upgrade of the session fails.

**Comment by pmolchanov2002** [comment]
If the old session is null and old user DN is null as well (seems like it's your case), session upgrade should be switched off in the LoginState.java:

```
        if(oldSession == null) {
                sessionUpgrade = false;
        }
        
        if (DEBUG.messageEnabled()) {
            DEBUG.message("LoginState.setSessionProperties()" +
                    " userDN is: " + userDN);
            DEBUG.message("LoginState.setSessionProperties()" +
                    " oldUserDN is: " + oldUserDN);
            DEBUG.message("LoginState.setSessionProperties()" +
                    " sessionUpgrade is: " + sessionUpgrade);
        }
```

**Comment by pmolchanov2002** [comment]
Added a pull request: https://github.com/OpenIdentityPlatform/OpenAM/pull/298

**Comment by vharseko** [comment]
fixed https://github.com/OpenIdentityPlatform/OpenAM/pull/298 thanks https://github.com/pmolchanov2002
