### ISSUE TITLE
Integrate to Web Application

### ISSUE THREAD

**Issue by LHRGB** [OpenIdentityPlatform/OpenAM#304]
Hi, 

does anybody know, if i can implement the Open IAM features into an existing web application?
Sorry if the questions sounds stupid, I am completely new into programming and have no experience at all.

Thank you!

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-Add-Authorization-and-Protect-Your-Application-With-OpenAM-and-OpenIG-Stack
