### ISSUE TITLE
Vulnerable javascript library - handlebars 4.4.2

### ISSUE THREAD

**Issue by gmedvethu** [OpenIdentityPlatform/OpenAM#314]
This version includes Cross-Site Scripting (XSS), Prototype Pollution and Arbitary JavsScript Execution vulnerabilies. More information: https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v453---november-18th-2019

**Comment by maximthomas** [comment]
@gmedvethu the lastest version contains upgrade for the library to 4.7.6 version.
