### ISSUE TITLE
vulnerable javascript library - jQuery-min 2.1.1

### ISSUE THREAD

**Issue by gmedvethu** [OpenIdentityPlatform/OpenAM#316]
This version includes a Cross-Site Scripting (XSS) vulnerability. More information:

- https://github.com/jquery/jquery/issues/2432
- https://bugs.jquery.com/ticket/9521
- https://bugs.jquery.com/ticket/11974
- https://snyk.io/vuln/SNYK-JS-JQUERY-174006
- http://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

**Comment by maximthomas** [comment]
Fixed in https://github.com/OpenIdentityPlatform/OpenAM/pull/327
