### ISSUE TITLE
What is considered a production-ready release?

### ISSUE THREAD

**Issue by rrialq** [OpenIdentityPlatform/OpenAM#321]
**Is your feature request related to a problem? Please describe.**
I don't know if there is a convention about releases (for example, Long Term Supported releases, even releases are ready for production use but odd don't, or minor versions are recommended updates always). I didn't found information about that.

**Describe the solution you'd like**
A clear and concise description of what is considered a production-ready release.

**Describe alternatives you've considered**

**Additional context**
OpenAM releases versions that are not mentioned in the blog. For example, last version 14.5.4 is not mentioned in the blog, but 14.5.3 do, so a question is inevitable: It is recommended 14.5.3 for production and 14.5.4 don't or last minor version is the recommended version?

**Comment by vharseko** [comment]
please use last community release
