### ISSUE TITLE
Bad policy resource pattern in the Quick Start Guide

### ISSUE THREAD

**Issue by Lauenburg** [OpenIdentityPlatform/OpenAM#325]
**Describe the bug**
Following the [Quick Start Guide](https://github.com/OpenIdentityPlatform/OpenAM/wiki/Quick-Start-Guide) step by step leads, after successful authentication and redirection to the resource, to a 403:`Forbidden You don't have permission to access / on this server.`. 

**To Reproduce**
Follow [Quick Start Guide](https://github.com/OpenIdentityPlatform/OpenAM/wiki/Quick-Start-Guide) step by step. 

**Expected behavior**
After successful authentication and redirect the resource displays "It works!". 

**Additional context**
According to the quick start guide, the resource URL of the policy should be set to `*://example:com/?`.  However, this leads to the error mentioned above. When setting the resource URL of the Policy instead to `http://www.example.com:80/*` the setup shows the expected behavior.

**Comment by maximthomas** [comment]
Thank you for the issue @Lauenburg, fixed doc

**Comment by fjbeli** [comment]
This issue is still exist after the changed in the doc. The pattern must be changed as mentioned above :
`*://www.example.com:*/*`

**Comment by maximthomas** [comment]
@fjbeli  updated the guide, pleas check
