### ISSUE TITLE
OpenAM IBM WAS - does it work

### ISSUE THREAD

**Issue by sverma37** [OpenIdentityPlatform/OpenAM#329]
I am using IBM WAS 9 and IBM SDK8. Does OpenIdentityPlatform OpenAM 14.* work on IBM Websphere?

**Comment by FireBurn** [comment]
It certainly used to, it's been a while since I've tested it

OpenAM Community Edition works on WAS8.5 with IBM Java 7 (if it's built with Oracle Java 7)

It also works with openliberty with openjdk-8 - that's what my testing has moved to

**Comment by sverma37** [comment]
It doesn't work on WAS9 + IBM JDK8. I get the error: 

[1/29/21 9:33:24:583 EST] 00000096 SystemOut     O amSecurity:01/29/2021 09:33:24:583 AM EST: Thread[WebContainer : 2,5,main]: TransactionId[2cc94b6f-a7b7-408d-8645-571f34c6c5cf-14]
**ERROR: AdminTokenAction: App user name or password is empty**
[1/29/21 9:33:24:584 EST] 00000096 SystemOut     O amSecurity:01/29/2021 09:33:24:583 AM EST: Thread[WebContainer : 2,5,main]: TransactionId[2cc94b6f-a7b7-408d-8645-571f34c6c5cf-14]
**ERROR: AdminTokenAction: FATAL ERROR: Cannot obtain Application SSO token**

Please note that I have all the recommended IBM related jvm arguments in WAS server.

**Comment by FireBurn** [comment]
I can try and help if you let me know how you configured OpenAM

**Comment by sverma37** [comment]
Below are the steps to recreate the issue:
1) Installed WAS9 base version and IBM SDK 8 on RHEL 8.2
2) Created a WebSphere instance server1
3) Added the generic jvm arguments to the server created above: -DamCryptoDescriptor.provider=IBMJCE -DamKeyGenDescriptor.provider=IBMJCE
4) Change the max heap size to 2GB
5) Downloaded the 14.2 openam war file from https://github.com/OpenIdentityPlatform/OpenAM/releases
6) Installed the war into WebSphere server created in step 2 "server1"
7) Change the class loading of the openam class loading to "parent last"
8) Restarted the server
9) Browse the URL http://<server_host>:9080/openam

The openam application opens. I use the "Default Configuration" option to configure openam which just requires password for "Default User" and "Default Policy Agent". Upon clicking "Create Configuration", the default configuration starts and fails with error "AdminTokenAction: FATAL ERROR: Cannot obtain Application SSO token., refer to [install.log] under /root/openam for more information.".

I have attached install.log from openam and systemOut.log from IBM WebSphere server as well. Let me know if you need more details.
[SystemOut.log](https://github.com/OpenIdentityPlatform/OpenAM/files/5895600/SystemOut.log)
[install.log](https://github.com/OpenIdentityPlatform/OpenAM/files/5895601/install.log)

**Comment by FireBurn** [comment]
Hi

I've done some investigating, when I try and compile OpenAM using the IBM 8.0 JDK I get the following errors:

[INFO] Compiling 230 source files to /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[39,24] error: cannot find symbol
  symbol:   class DerInputStream
  location: package sun.security.util
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[40,24] error: cannot find symbol
  symbol:   class DerOutputStream
  location: package sun.security.util
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[41,24] error: cannot find symbol
  symbol:   class DerValue
  location: package sun.security.util
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[42,24] error: cannot find symbol
  symbol:   class ObjectIdentifier
  location: package sun.security.util
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[43,24] error: cannot find symbol
  symbol:   class AVA
  location: package sun.security.x509
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[44,24] error: cannot find symbol
  symbol:   class Extension
  location: package sun.security.x509
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[45,24] error: cannot find symbol
  symbol:   class GeneralNames
  location: package sun.security.x509
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[46,24] error: cannot find symbol
  symbol:   class PKIXExtensions
  location: package sun.security.x509
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[47,24] error: cannot find symbol
  symbol:   class RDN
  location: package sun.security.x509
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[107,55] error: cannot find symbol
  symbol: class Extension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[152,12] error: cannot find symbol
  symbol:   class GeneralNames
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[153,12] error: cannot find symbol
  symbol:   class RDN
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[179,45] error: cannot find symbol
  symbol:   class GeneralNames
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[210,45] error: cannot find symbol
  symbol:   class RDN
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[341,11] error: cannot find symbol
  symbol:   class GeneralNames
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[348,11] error: cannot find symbol
  symbol:   class RDN
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[384,28] error: cannot find symbol
  symbol:   class GeneralNames
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[394,32] error: cannot find symbol
  symbol:   class RDN
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[556,40] error: cannot find symbol
  symbol:   class DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[556,19] error: cannot find symbol
  symbol:   class AVA
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[571,34] error: cannot find symbol
  symbol:   class RDN
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[571,43] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[186,12] error: cannot find symbol
  symbol: variable extensionId
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[186,27] error: cannot find symbol
  symbol:   variable PKIXExtensions
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[187,12] error: cannot find symbol
  symbol: variable critical
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[217,12] error: cannot find symbol
  symbol: variable extensionId
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[217,27] error: cannot find symbol
  symbol:   variable PKIXExtensions
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[218,12] error: cannot find symbol
  symbol: variable critical
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[238,12] error: cannot find symbol
  symbol: variable extensionId
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[238,27] error: cannot find symbol
  symbol:   variable PKIXExtensions
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[239,12] error: cannot find symbol
  symbol: variable critical
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[245,1] error: cannot find symbol
  symbol:   variable extensionValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[246,8] error: cannot find symbol
  symbol:   class DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[246,27] error: cannot find symbol
  symbol:   class DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[246,36] error: cannot find symbol
  symbol:   variable extensionValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[247,16] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[256,8] error: cannot find symbol
  symbol:   class DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[259,12] error: cannot find symbol
  symbol:   class DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[262,33] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[263,31] error: cannot find symbol
  symbol:   class GeneralNames
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[266,33] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[268,35] error: cannot find symbol
  symbol:   class RDN
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[283,25] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[294,25] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[309,25] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[319,25] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[436,8] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[436,34] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[437,16] error: cannot find symbol
  symbol: variable extensionValue
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[438,16] error: cannot find symbol
  symbol: variable extensionId
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[438,31] error: cannot find symbol
  symbol:   variable PKIXExtensions
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[439,16] error: cannot find symbol
  symbol: variable critical
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[442,8] error: cannot find symbol
  symbol:   variable super
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[454,2] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[454,31] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[458,12] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[458,52] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[460,16] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[460,45] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[463,39] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[463,20] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[466,16] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[466,45] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[469,39] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[469,20] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[473,35] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[473,16] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[478,12] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[478,58] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[480,52] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[480,33] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[486,12] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[486,56] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[488,52] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[488,33] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[493,5] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[493,35] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[497,25] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[497,6] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[502,12] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[502,48] error: cannot find symbol
  symbol:   class DerOutputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[504,52] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[504,33] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[508,12] error: cannot find symbol
  symbol: variable extensionValue
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[526,18] error: cannot find symbol
  symbol:   variable super
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[559,8] error: cannot find symbol
  symbol:   class DerInputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[559,33] error: cannot find symbol
  symbol:   class DerInputStream
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[560,8] error: cannot find symbol
  symbol:   class DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[562,8] error: cannot find symbol
  symbol:   class AVA
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[562,25] error: cannot find symbol
  symbol:   class AVA
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[564,12] error: cannot find symbol
  symbol:   class DerValue
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[565,26] error: cannot find symbol
  symbol:   class AVA
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[575,8] error: cannot find symbol
  symbol:   class AVA
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[575,26] error: cannot find symbol
  symbol:   class AVA
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[575,49] error: cannot find symbol
  symbol:   class AVA
  location: class IssuingDistributionPointExtension
[ERROR] /apps/was/jenkins/workspace/Compile_OpenAM_Test/OpenAM/openam-shared/src/main/java/com/iplanet/security/x509/IssuingDistributionPointExtension.java:[576,31] error: cannot find symbol
  symbol:   variable DerValue
  location: class IssuingDistributionPointExtension

From memory the missing things are deprecated in Oracle Java 8, but completely removed from IBM's Java 8

Is you really want to run this app on WebSphere, I'd recommend compiling it with JDK 7 (I've had success in the past) running with IBM Java 7.0 on WebSphere 8.5.5

**Comment by FireBurn** [comment]
I've had another look, only OpenAM Comunity Edition from https://github.com/ForgeRock/openam-community-edition builds with Java7

To get OpenIdentityPlatform OpenAM working it has to be build with 8 and run with Oracle or OpenJDK - so no IBM Java 8

OpenAM does work on Liberty and OpenLiberty with the above JVMs

**Comment by sverma37** [comment]
As per suggestion, we installed open 14.2.2 on IBM WLP with Oracle java 8. It is using Oracle java 8. The application opens in the browser and the default configuration also works fine. But as soon as I open the top level realm and click on any of the tabs on the left pane (example Data stores), it gives me the error: "**Unknown error. Please contact your Administrator**"

I have attached the below files:
1) server.xml for IBM wlp which shows the server/application configuration.
2) jvm.options for heap size of 2G
3) messages.log and ffdc.log which shows the error which we get.


[ffdc_21.02.04_11.37.53.0.log.txt](https://github.com/OpenIdentityPlatform/OpenAM/files/5945565/ffdc_21.02.04_11.37.53.0.log.txt)
[jvm.options.txt](https://github.com/OpenIdentityPlatform/OpenAM/files/5945566/jvm.options.txt)
[messages.log.txt](https://github.com/OpenIdentityPlatform/OpenAM/files/5945567/messages.log.txt)
[server.xml.txt](https://github.com/OpenIdentityPlatform/OpenAM/files/5945568/server.xml.txt)

**Comment by FireBurn** [comment]
I've just tested running https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2021-01-13_1459/openliberty-21.0.0.1.zip with https://github.com/OpenIdentityPlatform/OpenAM/releases/download/14.6.2/OpenAM-14.6.2.war

Using the following server.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<server description="new server">

    <!-- Enable features -->
    <featureManager>
        <feature>jsp-2.3</feature>
    </featureManager>

    <!-- To access this server from a remote client add a host attribute to the following element, e.g. host="*" -->
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  host="*"
                  httpsPort="9443" />

    <application id="openam" name="openam" contextRoot="openam" type="war" location="${server.config.dir}/apps/openam.war" />

    <!-- Default SSL configuration enables trust for default certificates from the Java runtime -->
    <ssl id="defaultSSLConfig" trustDefaultCerts="true" />
</server>
```

I don't see any errors when I click on the Data stores

I did have to add a closing slash to your application definition above

**Comment by sverma37** [comment]
The closing slash to the application definition did not work. 

So, I did a fresh installation of the whole thing on WLP and it worked. Thanks again!

**Comment by FireBurn** [comment]
No problem, glad I could be of help
