### ISSUE TITLE
Point to OpenAMCommunity

### ISSUE THREAD

**Issue by hdost** [OpenIdentityPlatform/OpenAM#337]
**Describe the bug**
The community edition moved in 2016 from https://github.com/ForgeRock/OpenAM-Community-Edition to https://github.com/OpenIdentityPlatform/OpenAM

**Expected behavior**
The old project should be archived after placing a notice in the README which points people to the new (this) location.

**Comment by vharseko** [comment]
https://github.com/ForgeRock/OpenAM-Community-Edition dead fork

**Comment by hdost** [comment]
I'm assuming this means no one has access to the old project to kill it. It may even be worth asking GitHub for a forward 🤷‍♀️

**Comment by vharseko** [comment]
owner FR: now he has no interest in supporting the community
