### ISSUE TITLE
Issue when trying to update Subjects within policy

### ISSUE THREAD

**Issue by glchua2** [OpenIdentityPlatform/OpenAM#341]
**Describe the bug**
When creating a new policy, Subjects cannot be modified and saved.

**To Reproduce**
1. Go to Authorization -> Policy Sets -> Select existing Policy Set -> click on +Add a Policy button.
2. Click on Subjects tab and you will be able to see message "The "Not..." logical operator can only accept one child" is shown even though All of option is selected.
3. Clicking on button +Add a Subject Condition or +Add a Logical Operator result in nothing happening.

**Expected behavior**
1. Message in Step 2 of "To Reproduce" should not appear
2. Adding Subject Condition and Logical Operator should work as intended.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome(88.0.4324.150), Firefox (85.0.2)

**Additional context**
Using latest version of OpenAM (14.6.2)
Refer to previous [issue](https://github.com/OpenIdentityPlatform/OpenAM/issues/69)

**Comment by sp193** [comment]
I am not able to replicate what @glchua2 mentioned. As we work on the same project, I no longer see this as being a problem with today's releases. So this issue may be closed.
