### ISSUE TITLE
Can't search user by user id

### ISSUE THREAD

**Issue by iloeng** [OpenIdentityPlatform/OpenAM#349]
**Describe the bug**
Can't search user by user id

**To Reproduce**
1. Signin OpenAM as admin
2. Go to 'realm' 
3. Click on 'Subjects'
4. Input user id into Search, and click search
5. See error, there will show nothing 

**Expected behavior**
should show user list

**Screenshots**
this system have many users, i just use these user as example.
![image](https://user-images.githubusercontent.com/31269745/109915995-c6d6ee80-7ced-11eb-8618-48a374c0841a.png)

search result:
![image](https://user-images.githubusercontent.com/31269745/109916195-2634fe80-7cee-11eb-99c1-3ab68fc9ee5b.png)
![image](https://user-images.githubusercontent.com/31269745/109916479-ace9db80-7cee-11eb-9bb7-73e056a9bc0e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [ chrome]
 - Version [OpenAM 14.5.1 Build d8b8db3cac (2020-March-11 23:25)]

**Additional context**

**Comment by maximthomas** [comment]
@mancheaka Hello, you can change `iplanet-am-admin-console-user-search-key` attribute in `iPlanetAMAdminConsoleService` form `cn` to your target attribute. You can do it using either ssoadm or change attribute in OpenDJ directly using LDAP client, for example, Apache Directory Studio
