### ISSUE TITLE
Can not access realm scripts page

### ISSUE THREAD

**Issue by SamyOteroGlez** [OpenIdentityPlatform/OpenAM#35]
**Describe the bug**
After starting the Docker container (using the docker file provided in the repo), doing an openAM default configuration, we are unable to access the realm scripts page, (it shows nothing). We are unable to upload any OIDC claim groovy script.
We are also receiving two errors in the chrome console
```
Uncaught SyntaxError: Unexpected token <            backgrid-select-all-0.3.5-min.js?v=14.1.1:7
Uncaught TypeError: Cannot read property 'extend' of undefined      ThemeableSelectAllCell.js?v=14.1.1:38 
```
It happened with versions: 14.1.1, 14.1.2, 14.1.3 and 14.1.4
I need to use at least version 14.1.1

**To Reproduce**
1. Start the docker image you provided (https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/14.1.1)
2. Do the default configuration
3. Go to the upload scripts section

**Expected behavior**
Be able to click on the realm scripts link and upload an OIDC claim groovy script.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 14.04
 - Browser chrome, firefox
 - Version chrome: Version 63.0.3239.108 (Official Build) (64-bit), firefox: Version 46.0.1

I look forward to hearing from you.

Regards,
Samy

**Comment by SamyOteroGlez** [comment]
An update.

We found that the issue is been caused by this file `/OpenAM-14.1.1/XUI/libs/backgrid-select-all-0.3.5-min.js` inside the .war file. It contains HTML instead of js. We believe the correct content of the file should be `https://raw.githubusercontent.com/cloudflare/backgrid-select-all/master/backgrid-select-all.js`.

I look forward to hearing from you.

Regards,
Samy

**Comment by SamyOteroGlez** [comment]
Solved.

I had to uncompress the war file, modify `/OpenAM-14.1.1/XUI/libs/backgrid-select-all-0.3.5-min.js` file with the content from `https://raw.githubusercontent.com/cloudflare/backgrid-select-all/master/backgrid-select-all.js` and rebuild again the way file by running `$ jar -cvf YOUR_WAR.war *`.

For this, I had to use my own Dockerfile, not the one you provided, and use the war file and the configurator from your repo.

Regards,
Samy

**Comment by SamyOteroGlez** [comment]
New Issue,

After saving the script, the list is still empty.

**Comment by SamyOteroGlez** [comment]
Thanks, a lot.

That fixed the blank page, but now after saving the OIDC claim script, when I go back, the list of scripts is still empty.

I look forward hearing from you.

Regards,
Samy

**Comment by dmaclam-pulse** [comment]
I am also able to recreate this issue. Looks like some of the other js assets are broken. 

TypeError: filter.query is not a function in openam/XUI/org/forgerock/openam/ui/common/util/BackgridUtils.js?v=14.1.1

Thanks,
Daniel

**Comment by vharseko** [comment]
please recheck issue in https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/14.1.5

**Comment by SamyOteroGlez** [comment]
Fixed!

Thanks!!!

**Comment by SamyOteroGlez** [comment]
I just notice that the script page is still busted, but only in chrome. I am using the latest version of chrome. I cant do an ajax request to load all the scripts. Looks like angular is failing. But this issue is not happening on firefox.

Regards,
