### ISSUE TITLE
UI issues with recent snapshots

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM#351]
Hi, I just updated from 257c088d43e128d0aeab059951f41b6313367341 to the latest snapshot and I'm noticing some unexpected UI glitches in the admin UI, for example:

* In the Realm > Services screen, the page title has the pull-right class that I did not remember was there, and the commands to the right have some weird doubling:
![immagine](https://user-images.githubusercontent.com/16761934/110666265-723de280-81c9-11eb-8c34-2841a7e748d7.png)

* In a service detail, the headers look off:
![immagine](https://user-images.githubusercontent.com/16761934/110666523-b4ffba80-81c9-11eb-9444-0b956b9e8ea3.png)

* In the Configure > Global Services section, the active tab indicators are missing:
![immagine](https://user-images.githubusercontent.com/16761934/110666810-f1cbb180-81c9-11eb-857e-4820f0e3d806.png)

I have tested with both firefox and chrome with incognito mode and caches disabled.

Firefox shows the following errors in the console:
![immagine](https://user-images.githubusercontent.com/16761934/110667533-a239b580-81ca-11eb-90a2-16822051d9cc.png)

Weirdly, Chrome does not show the same error (but still renders with the same problems).

**Comment by maximthomas** [comment]
fixed UI issues in the latest sources
