### ISSUE TITLE
Upgrade guide when using docker container

### ISSUE THREAD

**Issue by Hans-Maulwurf** [OpenIdentityPlatform/OpenAM#353]
Hey,
I'm using OpenAM and OpenDJ as docker container with /usr/openam/config and /opt/opendj/data as volumes, so the data/config is still there when I start a new instance of the container. At the moment I'm running the container with the version 4.4.5. Can I just replace the container with the newer version and the data/config is updated by itself or is there a upgrade guide for the docker setup?

**Comment by maximthomas** [comment]
@Hans-Maulwurf, Hello, OpenDJ should update itself without any additional actions. But anyway, make backup of your data before upgrade.

**Comment by Hans-Maulwurf** [comment]
Well and what about OpenAM? How to upgrade this?

**Comment by maximthomas** [comment]
@Hans-Maulwurf 
Just replace war file in a web server and restart the server. OpenAM will prompt to upgrade. Restart web server after upgrade.

**Comment by Hans-Maulwurf** [comment]
@maximthomas As mentioned in the title, I'm using the docker variant with volume of /usr/openam/config outside the container. Is this enough for just replacing the container, mounting the config-directory and starting the new docker container?

**Comment by maximthomas** [comment]
@Hans-Maulwurf yes, sure
