### ISSUE TITLE
OpenAM OAuth token issue not invalidate when multiple SSO servers

### ISSUE THREAD

**Issue by salman-khandu** [OpenIdentityPlatform/OpenAM#362]
There is an issue of token revocation when there is multiple SSO server configured. I have documented an issue here 
https://stackoverflow.com/questions/66948414/openam-oauth-token-issue-not-invalidate-when-multiple-sso-servers

Thank you

**Comment by vharseko** [comment]
OAuth2 tokens are stored in CTS persistence store. You need to check that CTS persistence store infrastructure works as expected (e.g. if it's replicated)
