### ISSUE TITLE
OpenAM Docker Image: Policy Sets Subject Condition cannot be set anymore

### ISSUE THREAD

**Issue by Lauenburg** [OpenIdentityPlatform/OpenAM#363]
**Describe the bug**
It is not possible to set a subject condition any more under: Authorization > Policy Sets > custom_policy > Subjects.
In the previous version, it was possible to set the condition "Authenticated Users" for the subjects "All of...".
However, while still able to select "All of..."  the console does not respond when clicking "+ Add a subject condition".  

By not setting this condition we run into a "403 Forbidden" error when trying to access a server protected by a web policy agent as explained in the [wiki-quick-start](https://github.com/OpenIdentityPlatform/OpenAM/wiki/Quick-Start-Guide) 

**To Reproduce**

Follow the [wiki-quick-start](https://github.com/OpenIdentityPlatform/OpenAM/wiki/Quick-Start-Guide)  until the step "Select Subjects tab and set type to Authenticated Users".

**Expected behavior**
Being able to set the subject condition like in the previous version.

**Screenshots**
![image](https://user-images.githubusercontent.com/29601467/113897543-42cfc500-97cb-11eb-9ace-f92ab812e9af.png)

**Desktop (please complete the following information):**
 - [Docker image](https://hub.docker.com/r/openidentityplatform/openam/)
 - Chrome
 - latest

**Comment by mquirion** [comment]
Have run into this exact same problem while following this instruction set to run OpenAM in K8S.
https://www.openidentityplatform.org/blog/how-to-run-openam-kubernetes

Anyone know a work-around? I tried using older versions of the image, and those are suffering startup failures.

**Comment by maximthomas** [comment]
@mquirion @Lauenburg Hi, I'm working on the issue, will fix it as soon as possible

**Comment by maximthomas** [comment]
@mquirion @Lauenburg Hello, I fixed the issue in the latest source, wait for the next release

**Comment by mquirion** [comment]
@maximthomas thanks!
