### ISSUE TITLE
Can't seem to specify the version to install

### ISSUE THREAD

**Issue by fbc** [OpenIdentityPlatform/OpenAM#369]
**Describe the bug**
Ran 
docker run -h openam-01.domain.com -p 8080:8080 --name openam-01 openidentityplatform/openam:13.5.0-RC2
got error 
unable to find image 'openidentityplatform/openam:13.5.0-RC2' locally
docker: Error response from daemon: manifest for openidentityplatform/openam:13.5.0-RC2 not found: manifest unknown: manifest unknown.

**To Reproduce**
try running the same command

**Expected behavior**
it should have installed the specified version

**Comment by vharseko** [comment]
check version list: https://hub.docker.com/r/openidentityplatform/openam/tags?page=1&ordering=last_updated <https://hub.docker.com/r/openidentityplatform/openam/tags?page=1&ordering=last_updated>

**Comment by fbc** [comment]
Yeah, 13.5 isn't even on the list anymore. thanks anyways.
