### ISSUE TITLE
Apache Tomcat 8.5.41 is EOL since 30 June 2018

### ISSUE THREAD

**Issue by AndreaVida** [OpenIdentityPlatform/OpenAM#373]
**Describe the bug**
Apache Tomcat 8.5.41 is EOL.
No security patches will be provided anymore for this product.

Migration to newer release should be considered.

**Comment by FireBurn** [comment]
That's Tomcat 8.0.x not the still in support 8.5.x

**Comment by AndreaVida** [comment]
Sorry my bad I took the wrong link. Is it 8.5.x still in full support? I can't find an official date even if some source (https://www.tomitribe.com/legal/lifecycle-policy/) claims EOL date of 8.5.x to be March 2019.

**Comment by vharseko** [comment]
8.5.x with full support
