### ISSUE TITLE
Update Tomcat to latest 8.5.x version to get recent security fixes 

### ISSUE THREAD

**Issue by AndreaVida** [OpenIdentityPlatform/OpenAM#374]
According to http://tomcat.apache.org/security-8.html#Apache_Tomcat_8.x_vulnerabilities several important vulnerabilities have been fixed in versions > 8.5.41.

Current version: 8.5.41 
Latest version: 8.5.68 
Latest version containing important security patches: 8.5.63

**Comment by vharseko** [comment]
please use last version 8.5.XX

**Comment by AndreaVida** [comment]
Sorry forgot to mention explicitly I was talking about OpenAM Docker image provided on Docker Hub: https://hub.docker.com/r/openidentityplatform/openam/ where Tomcat is already provided (at version 8.5.41).

**Comment by vharseko** [comment]
try latest tag openidentityplatform/openam:14.6.3 with Apache Tomcat/8.5.68

**Comment by AndreaVida** [comment]
Thanks!
