### ISSUE TITLE
OpenAM Cassandra Integration

### ISSUE THREAD

**Issue by shashikantkulkarni** [OpenIdentityPlatform/OpenAM#375]
Hello All,

I am trying to integrate Cassandra database as a datastore in OpenAM. I followed [this link](https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-Use-Apache-Cassandra-as-User-DataStore-in-OpenAM)

- Installed OpenAM as a container
- Installed Cassandra as a separate container
- Made sure the openam container can talk to Cassandra container
- Then deleted the embedded default datastore from OpenAM
- Then configured cassandra as per [this link](https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-Use-Apache-Cassandra-as-User-DataStore-in-OpenAM)
- Then under Subjects -> User -> New user trying to add a new user. 
- Failed with error  "No plug-ins configured for this operation"

Did I miss any step?
Can someone please help me here?

Thanks in advance.
Regards,
Shashikant

**Comment by shashikantkulkarni** [comment]
@vharseko Did you get time to look into this issue? Would you please update if possible? Thanks

**Comment by vharseko** [comment]
please check https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-Use-Apache-Cassandra-as-User-DataStore-in-OpenAM
