### ISSUE TITLE
Global Services not showing on latest Docker image of OpenAM

### ISSUE THREAD

**Issue by yuen-os** [OpenIdentityPlatform/OpenAM#384]
Global Services not showing on latest Docker image of OpenAM

following the [quick start guide]( https://github.com/OpenIdentityPlatform/OpenAM/wiki/Quick-Start-Guide) , on the Cookie Domain Configuration step on the UI the Global Services are not showing , it only shows "Configure default properties applied when creating new services." and upon doing an inspect on the browser it shows an error on this endpoint (500 status code) http://openam.example.com:8080/openam/json/global-config/services?_action=nextdescendents 

 [Docker image](https://hub.docker.com/layers/openidentityplatform/openam/latest/images/sha256-7fda33515006c61fdf71011cf65d40abee462686515f96461a7fbedd41bafd9b?context=explore)

**Steps to reproduce the behavior:**
1. follow the [quick start guide](https://github.com/OpenIdentityPlatform/OpenAM/wiki/Quick-Start-Guide)  up until the Cookie Domain Configuration
2. Navigate to Configure -> Global Services -> Platform -> Cookie Domain.
3. When navigate on this it shows "Configure default properties applied when creating new services."

**Expected behavior**
should show global services list

**Screenshots**
<img width="959" alt="gggg" src="https://user-images.githubusercontent.com/86647181/128334431-c713818d-8519-47c1-ab67-ecce89895c7e.PNG">

**Desktop**
 - OS: Windows 10 Enterprise version 20H2 build 19042.1110
 - Browser Google Chrome is up to date
 - Version 92.0.4515.131 (Official Build) (64-bit)

**Comment by maximthomas** [comment]
Seems there is a problem with Docker image, not with OpenAM itself. As a tempopery workaround I suggest you to use the following command to run OpenAM Docker image
```bash
 docker run --env CATALINA_OPTS="-Xmx2048m -server -Dcom.iplanet.services.configpath=/usr/openam/config -Dcom.sun.identity.configuration.directory=/usr/openam/config"  -h openam.example.com -p 8080:8080 --name openam openidentityplatform/openam
```
Add `CATALINA_OPTS` environment variable with `com.iplanet.services.configpath` and `com.sun.identity.configuration.directory` options

**Comment by yuen-os** [comment]
thanks @maximthomas , it's working fine on my end now.

**Comment by maximthomas** [comment]
@yuen-os glad I could help
