### ISSUE TITLE
Issue Building OpenAM from source

### ISSUE THREAD

**Issue by sudipta1411** [OpenIdentityPlatform/OpenAM#386]
I am trying to build the OpenAM from source.

My System Config : 
OS : elementary OS (5.1.7 Hera)
Kernel : 5.4.0-74-generic
Java: java-15 (JAVA_HOME=/usr/lib/jvm/java-15-oracle)
Apache Maven 3.6.0

I cloned the repository and run the command `mvn install -f OpenAM`. While building I first got the error 

    Compilation failure
    [ERROR] ~/OpenAM/openam-core/src/test/java/org/forgerock/openam/setup/TestSetupHelper.java:[48,65] error: reference to newFileSystem is ambiguous
    [ERROR]   both method newFileSystem(Path,ClassLoader) in FileSystems and method newFileSystem(Path,Map<String,?>) in FileSystems match

I casted the `null` to ClassLoader in the specified file and it went away (This is well known). But Now I got the error

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project openam-core: There are test failures.
    [ERROR] 
    [ERROR] Please refer to /home/sudipta/SID_IDP/OpenAM/openam-core/target/surefire-reports for the individual test results.
    [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
    [ERROR] There was an error in the forked process
    [ERROR] An error occurred while instantiating class 
    com.iplanet.dpro.session.service.SessionServerConfigTest: Cannot create a new instance of test class class com.iplanet.dpro.session.service.SessionServerConfigTest
    [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
    [ERROR] An error occurred while instantiating class com.iplanet.dpro.session.service.SessionServerConfigTest: Cannot create a new instance of test class class com.iplanet.dpro.session.service.SessionServerConfigTest
    [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:675)
    [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
    [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:248)
    [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1217)
    [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1063)
    [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:889)
    [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
    [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
    [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
    [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
    [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
    [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
    [ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
    [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
    [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
    [ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
    [ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
    [ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    [ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
    [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
    [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    [ERROR] 
    [ERROR] -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
    [ERROR] 
    [ERROR] After correcting the problems, you can resume the build with the command
    [ERROR]   mvn <goals> -rf :openam-core

I have no idea why is this happening. Can someone please help?

I have also used java-10, still the same issue.

**Comment by maximthomas** [comment]
@sudipta1411 to build OpenAM from source you should use JDK 8

**Comment by sudipta1411** [comment]
@maximthomas  , thanks for the comment.
