### ISSUE TITLE
OpenAM server gets down on node Side when there are too many calls

### ISSUE THREAD

**Issue by ghost** [OpenIdentityPlatform/OpenAM#387]
We are using open AM in our project which is in node. We save policies of our applications (like files on windows) on openAM but when there are too many calls to update the policies of an application then the server gets down.

**Comment by maximthomas** [comment]
@dev-ah please, provide more info. 
What do you mean by gets down? 
Slow response or crashing? Do you have exception call stack?
Have you tried to analyze thread dump or java heap?
Do you use OpenIG or Policy Agent? 
Which application causes frequent calls? 
Why are you updating the policies so frequently?

**Comment by vharseko** [comment]
cannot reproduce
