### ISSUE TITLE
OpenAM Build failed 

### ISSUE THREAD

**Issue by viruls** [OpenIdentityPlatform/OpenAM#39]
**Describe the bug**
While building the binary from source , Getting an error as shown in the attached screenshot.

**To Reproduce**
1. download the source git clone https://github.com/OpenIdentityPlatform/OpenAM.git
2. open command prompt and navigate to OpenAM folder upto the folder where pom.xml present
3. run mvn clean install

**Expected behavior**

**Screenshots**
![error](https://user-images.githubusercontent.com/1412321/40620182-7175f2d2-62ca-11e8-8f37-2d5a839f8d53.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
- JDK 1.8
-MVN 3.5.3

Thanks,

**Comment by vharseko** [comment]
please read https://github.com/OpenIdentityPlatform/OpenAM#how-to-build 

```bash
git clone --recursive  https://github.com/OpenIdentityPlatform/OpenAM.git
mvn -DskipTests -Dmaven.javadoc.skip=true install -f OpenAM/OpenDJ/forgerock-parent
mvn -DskipTests -Dmaven.javadoc.skip=true install -f OpenAM/OpenDJ -P\!distribution
mvn install -f OpenAM
```

**Comment by viruls** [comment]
Hi there,

Thanks for your prompt response, 

But When I use the below command, 
git clone --recursive  https://github.com/OpenIdentityPlatform/OpenAM.git
I am getting the following error,
![error](https://user-images.githubusercontent.com/1412321/40620896-24befa26-62cd-11e8-840f-01da8a0f7528.PNG)

Please advise.

**Comment by vharseko** [comment]
please try before clone

git config --system core.longpaths true

**Comment by viruls** [comment]
Hi Vharseko,

Thanks for the solution, Very helpful.

Thank you once again.

Cheers,

**Comment by viruls** [comment]
[build.log](https://github.com/OpenIdentityPlatform/OpenAM/files/2054006/build.log)
 
Please find the attached log.

Thanks,
