### ISSUE TITLE
Reflected XSS on /openam/json/realm-config/agents/2.2_Agent

### ISSUE THREAD

**Issue by AskenzSec** [OpenIdentityPlatform/OpenAM#396]
Hello Team, you will find enclosed a XSS vulnerability we found during a pentest.

**Describe the bug**
Reflected XSS on /openam/json/realm-config/agents/2.2_Agent using malicious _queryFilter param + _mimeType = text/html

**To Reproduce**
1. http://localhost:7080/openam/json/realm-config/agents/2.2_Agent?_queryFilter=%22%3E%3Cscript%3Ealert(%27XSS%27)%3C%2fscript%3E&_mimeType=text/html
2. See alert box displayed

**Screenshots**
![xss](https://user-images.githubusercontent.com/1435052/133004117-0bf3fbf8-622f-45b3-9bb7-500eb40888ae.png)

**Additional context**
The version tested was OpenAM 14.6.4 Build 55b85d9041 (2021-July-28 09:18)
Join OpenAM Community

**Comment by maximthomas** [comment]
@Fisjkars thank you for the issue, fixed in https://github.com/OpenIdentityPlatform/commons project
