### ISSUE TITLE
OpenAM Build Failed

### ISSUE THREAD

**Issue by viruls** [OpenIdentityPlatform/OpenAM#40]
**Is your feature request related to a problem? Please describe.**
Followed the instructions to build the OpenAM on windows with JDK1.8 and MVN 3.5

But failed with the below error on executing the 3rd command which is , 
mvn -DskipTests -Dmaven.javadoc.skip=true install -f OpenAM/OpenDJ -P\!distribution
 

![image](https://user-images.githubusercontent.com/1412321/40631469-8ad8b21a-630f-11e8-917e-f113278142e0.png)

Please advise how to fix this issue.

Thanks in advance.

**Comment by vharseko** [comment]
please attach full build log

**Comment by viruls** [comment]
Hi Vharseko,

Please find the attached file, 
[build.log](https://github.com/OpenIdentityPlatform/OpenAM/files/2046926/build.log)

Thank you once again.

**Comment by vharseko** [comment]
please run 

C:\Gamatech\Java\jdk1.8.0_45\jre\bin\java -Dorg.forgerock.opendj.gendoc=true -Dorg.opends.server.ServerRoot=C:\Users\narendra\AppData\Local\Temp\ -Dorg.opends.quicksetup.Root=/path/to/opendj -Dcom.forgerock.opendj.ldap.tools.scriptName=create-rc-script -Dorg.forgerock.opendj.gendoc.trailing=<xinclude:include href='exit-codes-0-gt0.xml' /><xinclude:include href='create-rc-script-examples.xml' /> -classpath D:\workspace\OpenAM\OpenDJ\opendj-doc-generated-ref\target\opendj\lib\bootstrap.jar;D:\workspace\OpenAM\OpenDJ\opendj-doc-generated-ref\target/dependency/freemarker-2.3.28.jar org.opends.server.tools.CreateRCScript —help

and attach output

**Comment by viruls** [comment]
Executed the command but it got struck saying the below, 

Listening for transport dt_socket at address: 8000

**Comment by vharseko** [comment]
try run without "suspend=y"

**Comment by viruls** [comment]
Dear Vharseko,

Executed without suspend=Y and the log got struck saying,
Listening for transport dt_socket at address: 8000

**Comment by vharseko** [comment]
@maximthomas need test build OpenDJ on windows

**Comment by viruls** [comment]
Hi Both,
Is there any workaround to make it success, Please advise.
Thanks in advance.

**Comment by vharseko** [comment]
please rerun with -Dorg.forgerock.opendj.gendoc=true -> -Dorg.forgerock.opendj.gendoc=false
and attach output

**Comment by vharseko** [comment]
fix https://github.com/OpenIdentityPlatform/OpenDJ/commit/2246d4cad9203461ae541094380d00a326ce34a4

for test

```bash
git clone --recursive  https://github.com/OpenIdentityPlatform/OpenDJ.git
mvn -DskipTests -Dmaven.javadoc.skip=true install -f OpenDJ/forgerock-parent
mvn -DskipTests -Dmaven.javadoc.skip=true install -f OpenDJ -P\!distribution
```

**Comment by viruls** [comment]
Hi , 
We are getting the below error while running the 3rd command for the test, 

![image](https://user-images.githubusercontent.com/1412321/40714100-439f1ea4-6434-11e8-907e-cd4f732f16f3.png)

**Comment by vharseko** [comment]
please attach full build log

**Comment by viruls** [comment]
[build.log](https://github.com/OpenIdentityPlatform/OpenAM/files/2054159/build.log)
Please find the attached log.

**Comment by viruls** [comment]
Hi There,

In the meanwhile , Please see if you can provide steps to download and build the OpenAM from a different branch.

Thanks,

**Comment by maximthomas** [comment]
Hello, @viruls, try to build with command
```mvn -DskipTests -Dmaven.javadoc.skip=true install -f OpenDJ -P !distribution``` (without slash)

**Comment by viruls** [comment]
Hi Vharseko,

We are able to compile and build the binary from the master branch.

Thanks a ton.
