### ISSUE TITLE
[security] XXE by parsing SAML response

### ISSUE THREAD

**Issue by h1analyts** [OpenIdentityPlatform/OpenAM#407]
https://github.com/OpenIdentityPlatform/OpenAM/blob/da05a2f102161c5cbbc091ad52f34a3c2cd6ee68/openam-federation/openam-federation-library/src/main/csharpsource/Fedlet/Fedlet/source/Saml2/ServiceProviderUtility.cs#L290

This code is vulnerable to XXE when the SAML response is parsed. It is missing the following code to secure the code

xmlDoc.XmlResolver = null;

One of our clients has been attacked via XXE due to this unpatched library.

Best regards,
turtle_shell from HackerOne

**Comment by maximthomas** [comment]
@h1analyts thank you for the issue, fixed, see #408 PR
