### ISSUE TITLE
New Source Code

### ISSUE THREAD

**Issue by FireBurn** [OpenIdentityPlatform/OpenAM#42]
Not sure if you're aware but the CDDL parts of Forgerocks products can be found here:

Open Source Zip Archives Version 5.0:

ForgeRock Access Management: (AM-cddl-sources-5.0.0.zip http://info.forgerock.com/z0Nb1xT000aUkNvpP2c0R00)
ForgeRock Identity Gateway: (IG-cddl-sources-5.0.0.zip http://info.forgerock.com/R00TabpUNx001020PQRvfk0)
ForgeRock Directory Services: (DS-cddl-sources-5.0.0.zip http://info.forgerock.com/wUbRkaxPT00002pd00N1O0v)
ForgeRock Identity Management: (IDM-cddl-sources-5.0.0.zip http://info.forgerock.com/Q0vR0bU0PP1TN0kpx00ea20)
Open Source Zip Archives Version 5.5:

Open Source Zip Archives Version 5.5:

ForgeRock Access Management: (AM-cddl-sources-5.5.1.zip http://info.forgerock.com/HP0010N0k2Jb0Ra0TsU00Mx)
ForgeRock Identity Gateway: (IG-cddl-sources-5.5.0.zip http://info.forgerock.com/gN0bakT0N10sUR0xP000K02)
ForgeRock Directory Services: (DS-cddl-sources-5.5.0.zip http://info.forgerock.com/hT2sOaU00P000Nx0k010RLb)
ForgeRock Identity Management: (IDM-cddl-sources-5.5.0.zip http://info.forgerock.com/a0100T0sNP0b00MRPUk0a2x)

**Comment by vharseko** [comment]
moved to wiki https://github.com/OpenIdentityPlatform/OpenAM/wiki/CDDL-parts-of-Forgerocks-products
