### ISSUE TITLE
Create a relationship between a Role and a Resource using the groovy script

### ISSUE THREAD

**Issue by ivanbc613** [OpenIdentityPlatform/OpenAM#450]
Hello,

I would like to be able to create a relationship between a Role object and a Resource object while importing data from a CSV using a groovy script. 

I've looked at the javadocs but the Role object doesn't seem to have a fitting function (see screenshot attached).

I'm using version 4.2.0.7, is there a solution? Or should I use a direct db connection?
If so, are there any particular conditions or I just need to match the ids? 

Thank you

![image](https://user-images.githubusercontent.com/98334879/150812799-022f5b7c-9819-498d-9b7d-1d2ae3b05404.png)

**Comment by vharseko** [comment]
incorrect   project
