### ISSUE TITLE
Issue while building the release branch 12,13,14

### ISSUE THREAD

**Issue by amit043** [OpenIdentityPlatform/OpenAM#452]
Hi ,

I was  trying to build the release branch but it seems it is referring to private forgerock repo so it failed the maven build.

can you please suggest a way to build the open source version non master branch as we are planning to use it 
and we want a stable release which we can build and deploy.

Thanks
Amit

**Comment by maximthomas** [comment]
Hi, 
At lease the latest stable https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/14.6.4 release built with open source repo

**Comment by srivasud** [comment]
Hi Thomas, Thanks for the response. Unfortunately, we can't use 14.6.4. It will be a huge leap for us to use 14.6.4. We are looking for ways to build 10.1.0.Xpress, 11, 12 versions of OpenAM. Please let us know if anyone is successful in building it. It hits the private repo of Forgerock when building. Is there any way we can get authenticated to download these dependent artifacts?

**Comment by FireBurn** [comment]
Take a look at the PRs on https://github.com/ForgeRock/openam-community-edition/pulls it should be enough to get 11.0.3 building

**Comment by psharmafico** [comment]
Hi, we did pulled in all the PRs from https://github.com/ForgeRock/openam-community-edition/pulls but still failing to build

Failed to read artifact descriptor for external:jaxrpc-impl:jar:1.1.3_01-041406: Could not transfer artifact external:jaxrpc-impl:pom:1.1.3_01-041406 from/to forgerock-internal (https://maven.forgerock.org/repo/internal): Not authorized , ReasonPhrase:Unauthorized.
Looks like need to signin/login to solve this or similar dependency ? any alternative for this ..

**Comment by PrashantSharma49** [comment]
Tried to build by pulling in all the PRs mentioned in https://github.com/ForgeRock/openam-community-edition/pulls 
Still failing.

Failed to read artifact descriptor for external:jaxrpc-impl:jar:1.1.3_01-041406: Could not transfer artifact external:jaxrpc-impl:pom:1.1.3_01-041406 from/to forgerock-internal (https://maven.forgerock.org/repo/internal): Not authorized , ReasonPhrase:Unauthorized.
Looks like need to signin/login to solve this or similar dependency ? any alternative for this ..

**Comment by FireBurn** [comment]
Look in the binaries directory....

**Comment by PrashantSharma49** [comment]
Thanks, that helped, we were able to build using the binaries and script provided.
