### ISSUE TITLE
Issue while building the release branch 10.1.0-Xpress, 11, 12,13,14

### ISSUE THREAD

**Issue by srivasud** [OpenIdentityPlatform/OpenAM#453]
Hi,
This is the same issue reported in https://github.com/OpenIdentityPlatform/OpenAM/issues/452.
We have an old OpenAM 10.1.0-Xpress. We have a need to build due to new enhancements that we need to do.
Unfortunately at the moment, we can't upgrade to bit higher versions. We tried building 11, 12, 13, and even 14.0.0. Unable to build due to dependent artifacts in the ForgeRock private repositories. 
So the question is
1. Is there any way or anyone successful building one of these old branches?
2. Is there any way to get authenticated to build these old branches?
Please let us know.
Thanks

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenAM/blob/master/SECURITY.md
