### ISSUE TITLE
Missing classes in 11.0.3 ce

### ISSUE THREAD

**Issue by PrashantSharma49** [OpenIdentityPlatform/OpenAM#454]
When trying to build my project upon upgrading the open am version from 10.1.0.Xpress to 11.0.3 getting compilation errors 

package edu.emory.mathcs.backport.java.util does not exist
package org.forgerock.openam.oauth2.store.impl does not exist
package com.sun.messaging.jmq.io does not exist
package org.forgerock.openam.ext.cts does not exist

com.sun.identity.saml.xmlsig.OfflineResolver is not abstract and does not override abstract method engineCanResolveURI(org.apache.xml.security.utils.resolver.ResourceResolverContext) in org.apache.xml.security.utils.resolver.ResourceResolverSpi
no suitable constructor found for ResourceResolverException(java.lang.String,java.lang.Object[],org.w3c.dom.Attr,java.lang.String)
 constructor org.apache.xml.security.utils.resolver.ResourceResolverException.ResourceResolverException(java.lang.String,java.lang.Object[],java.lang.String,java.lang.String) is not applicable
[ERROR]       (argument mismatch; org.w3c.dom.Attr cannot be converted to java.lang.String)
[ERROR]     constructor org.apache.xml.security.utils.resolver.ResourceResolverException.ResourceResolverException(java.lang.Exception,java.lang.String,java.lang.String,java.lang.String) is not applicable
[ERROR]       (argument mismatch; java.lang.String cannot be converted to java.lang.Exception)
[ERROR]     constructor org.apache.xml.security.utils.resolver.ResourceResolverException.ResourceResolverException(java.lang.String,java.lang.Exception,java.lang.String,java.lang.String) is not applicable
[ERROR]       (argument mismatch; java.lang.Object[] cannot be converted to java.lang.Exception)
[ERROR] com/sun/identity/saml/xmlsig/OfflineResolver.java:[76,16] no suitable constructor found for ResourceResolverException(java.lang.String,java.io.IOException,org.w3c.dom.Attr,java.lang.String)
[ERROR]     constructor org.apache.xml.security.utils.resolver.ResourceResolverException.ResourceResolverException(java.lang.String,java.lang.Object[],java.lang.String,java.lang.String) is not applicable
[ERROR]       (argument mismatch; java.io.IOException cannot be converted to java.lang.Object[])
[ERROR]     constructor org.apache.xml.security.utils.resolver.ResourceResolverException.ResourceResolverException(java.lang.Exception,java.lang.String,java.lang.String,java.lang.String) is not applicable
[ERROR]       (argument mismatch; java.lang.String cannot be converted to java.lang.Exception)
[ERROR]     constructor org.apache.xml.security.utils.resolver.ResourceResolverException.ResourceResolverException(java.lang.String,java.lang.Exception,java.lang.String,java.lang.String) is not applicable
[ERROR]       (argument mismatch; org.w3c.dom.Attr cannot be converted to java.lang.String)

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenAM/blob/master/SECURITY.md
