### ISSUE TITLE
Login with Users from AD Authentication Module Failed with Forbidden error

### ISSUE THREAD

**Issue by viruls** [OpenIdentityPlatform/OpenAM#46]
Getting Forbidden Error while trying to login with users from AD Auth module,

url is : http://ssoserver.nademo.com;8080/sso/XUI/?module=ADModule

Please advise.

Thanks,

**Comment by viruls** [comment]
Found this is similar to below,
https://bugster.forgerock.org/jira/browse/OPENAM-10149

**Comment by vharseko** [comment]
please attach log with error

**Comment by viruls** [comment]
![01](https://user-images.githubusercontent.com/1412321/40774300-d293f18e-64f7-11e8-9f00-e592a078bee6.PNG)
[sso.zip](https://github.com/OpenIdentityPlatform/OpenAM/files/2057604/sso.zip)
Please find the attached files.

Thanks,

**Comment by vharseko** [comment]
* can you view AD users in Subjects realm (need Datastore Active Directory config)  ?
* Access Control - realm - Authentication - All Core Settings - User Profile mode is set to ignored ?

**Comment by viruls** [comment]
AD is just configured under Modules 
we have only one Datastore which is OOTB embedded one in our env
set User Profile to Ignore state.

**Comment by viruls** [comment]
![image](https://user-images.githubusercontent.com/1412321/40791064-22b4565a-6529-11e8-8739-fe15bc6489a5.png)

**Comment by tupyy** [comment]
I have the same problem. I think this is related with *OPENAM-9898* bug. when I switch off the XUI interface it works.

**Comment by maximthomas** [comment]
@viruls @tupyy, I can't reproduce the issue. Could you please attach the screenshot of your AD module settings, especially the `Return User DN to DataStore` setting value?

**Comment by tupyy** [comment]
not relevant for me anymore. Thanks
