### ISSUE TITLE
Creation of Authentication Module & Authorization Policies Need restart of OpenAM ?

### ISSUE THREAD

**Issue by viruls** [OpenIdentityPlatform/OpenAM#47]
After creating the Authentication Module  , It was not listing under Modules and also Authentication chain is not listing the newly created module, Must restart the OpenAM Application Server to see it back in the Authentication Module Lists /Authentication chain drop down.

Also, If we try to create authorization Policies we are having this similar issue.

tomcat 8
JDK 8

Binary Build from Master Branch, Please advise

**Comment by vharseko** [comment]
this problem in XUI or old UI ?

**Comment by viruls** [comment]
XUI

**Comment by deftdawg** [comment]
Same as #15

**Comment by maximthomas** [comment]
@viruls, here is a workaround: after first start ang configuration you need restart container, so modules will appear just after you created them. I'll try figure out what's happening, at fist start of OpenAM.
