### ISSUE TITLE
Build release/13.0.0

### ISSUE THREAD

**Issue by viruls** [OpenIdentityPlatform/OpenAM#48]
Hi There,

We would like to build release/13.0.0 , Could you please advise them how to overcome forgerock maven repo issues.

Also please provide the steps to build/compile the release/13.0.0 branch

Source code checked out from github using the below command,
git clone -b release/13.0.0 --recursive https://github.com/OpenIdentityPlatform/OpenAM.git

Please advise.

Thanks,

**Comment by vharseko** [comment]
release/13.0.0 not supported

**Comment by viruls** [comment]
Hi,

May I know the recent stable version branch as we found some issues in master branch, we would like to go with Stable branch, Please advise.

Thanks,

**Comment by vharseko** [comment]
you can download direct from FR https://backstage.forgerock.com/downloads/browse/am/archive?path=%2FOpenAM%20Enterprise%2F13.0.0
