### ISSUE TITLE
SSOConfigurator issue with 404

### ISSUE THREAD

**Issue by capmatch** [OpenIdentityPlatform/OpenAM#492]
**Describe the bug**
Hi all, just some question about the SSOconfigurationer. Since i would like to automate the configuration store setup. So i am now trying openam-configurator-tool-14.6.4.jar but running

java -jar openam-configurator-tool-14.6.4.jar --file config.txt
null
Configuration Failed.  The server returned error code :404

**To Reproduce**
ACCEPT_LICENSES=true
actionLink = createConfig
DEPLOYMENT_URI=/openam
ADMIN_CONFIRM_PWD = testing123
ADMIN_PWD = testing123
AM_ENC_KEY = 
AMLDAPUSERPASSWD = abcabc123
AMLDAPUSERPASSWD_CONFIRM = abcabc123
BASE_DIR = C:/Users/capho/openamSP
COOKIE_DOMAIN = sp.example.net
DATA_STORE = embedded
DIRECTORY_ADMIN_PORT = 4444
DIRECTORY_JMX_PORT = 1689
DIRECTORY_PORT = 50389
DIRECTORY_SERVER = localhost
DIRECTORY_SSL = SIMPLE
DS_DIRMGRDN = cn=Directory Manager
DS_DIRMGRPASSWD = testing123
ie7fix = 25
locale = en_US
PLATFORM_LOCALE = en_US
ROOT_SUFFIX = dc=openam,dc=openidentityplatform,dc=org
SERVER_HOST = sp.example.net
SERVER_PORT = 8082
SERVER_URI = http://sp.example.net:8082/openamSP/config/wizard/wizard.htm
SERVER_URL = http://sp.example.net:8082
SITE_CONFIGURATION_MAP = {wizardLoadBalancerSiteName=LB, wizardLoadBalancerURL=http://lb.example.com/lb}
wizardLoadBalancerSiteName = LB
wizardLoadBalancerURL = http://lb.example.com/lb

**Comment by maximthomas** [comment]
Seems, there is a typo in your `SERVER_URI` parameter because it mismatches `DEPLOYMENT_URI=/openam`
