### ISSUE TITLE
INFO] OpenAM RIA Web UI .................................. FAILURE [ 34.229 s] [

### ISSUE THREAD

**Issue by vharseko** [OpenIdentityPlatform/OpenAM#5]
https://travis-ci.org/OpenIdentityPlatform/OpenAM/builds/306179875

[INFO] --- frontend-maven-plugin:1.1:npm (npm-install) @ openam-ui-ria ---
[INFO] Running 'npm install' in /Users/vharseko/git/OpenIdentityPlatform/OpenAM/openam-ui/openam-ui-ria
[WARNING] npm WARN deprecated babel-preset-es2015@6.18.0: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
[WARNING] npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
[ERROR] npm ERR! Darwin 17.2.0
[ERROR] npm ERR! argv "/Users/vharseko/git/OpenIdentityPlatform/OpenAM/openam-ui/openam-ui-ria/node/node" "/Users/vharseko/git/OpenIdentityPlatform/OpenAM/openam-ui/openam-ui-ria/node/node_modules/npm/bin/npm-cli.js" "install"
[ERROR] npm ERR! node v4.6.2
[ERROR] npm ERR! npm  v3.10.9
[ERROR] npm ERR! code E404
[ERROR] 
[ERROR] npm ERR! 404 Not Found: repo
[ERROR] npm ERR! 404 
[ERROR] npm ERR! 404  'repo' is not in the npm registry.
[ERROR] npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
[ERROR] npm ERR! 404 It was specified as a dependency of 'commander'
[ERROR] npm ERR! 404 
[ERROR] npm ERR! 404 Note that you can also install from a
[ERROR] npm ERR! 404 tarball, folder, http url, or git url.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /Users/vharseko/git/OpenIdentityPlatform/OpenAM/openam-ui/openam-ui-ria/npm-debug.log
[INFO] ------------------------------------------------------------------------

**Comment by maximthomas** [comment]
fixed with 4995cf67e587f24429c53a2df1356285568cbe2a commit
