### ISSUE TITLE
Restlet warning about "Pragma" header

### ISSUE THREAD

**Issue by BalSzabo** [OpenIdentityPlatform/OpenAM#505]
Our OpenAM docker container logs are full of the following warning message:

__WARNING [http-nio-8080-exec-48] org.restlet.engine.header.HeaderUtils.addExtensionHeaders Addition of the standard header "Pragma" is discouraged as a future version of the Restlet API will directly support it.__

We have not found how to eliminate this annoying log message.
OpenAM version: 14.6.4

**Comment by maximthomas** [comment]
This message warns about the 'Pragma' header because it could be used in a future version of OpenAM. Therefore, you should consider avoiding its usage.
