### ISSUE TITLE
Documentation on how to start openam and opendj in docker is missing

### ISSUE THREAD

**Issue by grchis** [OpenIdentityPlatform/OpenAM#509]
**Is your feature request related to a problem? Please describe.**
There is no documentation on how to start openam and opendj locally, each one in separate docker containers (not with embeded opendj)

**Describe the solution you'd like**
Documentation with clear steps on how to start locally these two services.

**Comment by maximthomas** [comment]
https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-Start-OpenAM-and-OpenDJ-in-Separate-Docker-Contaners
