### ISSUE TITLE
Security vulnerability allowing authenticated user to impersonate an arbitrary user

### ISSUE THREAD

**Issue by randomdude** [OpenIdentityPlatform/OpenAM#513]
I've discovered a serious security vulnerability in one of the OpenAM authentication modules, allowing an authenticated user to authenticate as any other user, without any interaction by the victim user nor an administrator. I've reproduced this bug in a recent build via the Docker container.

**Comment by vharseko** [comment]
Hi, send details vharseko@3a-systems.ru
