### ISSUE TITLE
WSFED Error After User Authentication (Accessing IDP SSO Initiated SSO URL) 

### ISSUE THREAD

**Issue by viruls** [OpenIdentityPlatform/OpenAM#52]
Dear Experts,

We tried to implement WSFED with our OpenAM as IDP.

And when we tried to access IDP Initiated SSO URL say,
http://sso.nademo.com:8080/sso/WSFederationServlet/metaAlias/idpwsfed?wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline

we are able to redirect to login page and after valid authentication, 

we are seeing the below error,

![image](https://user-images.githubusercontent.com/1412321/41359135-6af69b66-6f5c-11e8-93a1-74f7b459af21.png)

Please help us to fix this issue.

Thanks in advance.

Thanks,

**Comment by vharseko** [comment]
Please, describe work around

**Comment by viruls** [comment]
Configuration Problem (Signing Certificate not assigned in IDP settings)  but misleading error.
