### ISSUE TITLE
Failed while compiling the code on Windows 8

### ISSUE THREAD

**Issue by cscs-nchalla** [OpenIdentityPlatform/OpenAM#545]
I am on Windows 8 with 
JDK 1.8 (64 bit)
MVN 3.8.6 
And while trying to compile the OpenAM source code, getting the following error...

![Screen Shot 2022-10-04 at 9 25 02 PM](https://user-images.githubusercontent.com/109073980/193908373-8ee87bed-770c-41b6-bc4f-b423cbb9ab1b.png)
![Screen Shot 2022-10-04 at 9 25 19 PM](https://user-images.githubusercontent.com/109073980/193908377-d476ea75-863f-4304-8bf5-04798a0e5750.png)

Could you please advise how to fix this issue, Thanks!

**Comment by maximthomas** [comment]
@cscs-nchalla 
Could you please attach the log
![image](https://user-images.githubusercontent.com/7863782/205287555-e95c4d77-b92c-43ef-a7cb-54c66080470d.png)

**Comment by maximthomas** [comment]
can't reproduce the issue
