### ISSUE TITLE
Can't create Policy Set in 14.6.6

### ISSUE THREAD

**Issue by viruls** [OpenIdentityPlatform/OpenAM#546]
Login to OpenAM
Navigate to Authorization --> Policy Sets --> Click on New Policy Set and observing an error message as shown below, Even if I click on create I don't see any response.

![Screen Shot 2022-10-08 at 12 10 48 AM](https://user-images.githubusercontent.com/1412321/194669813-21698c6e-1a0d-4e5e-be21-c894ef3deb8e.png)

![Screen Shot 2022-10-08 at 12 11 19 AM](https://user-images.githubusercontent.com/1412321/194669815-78d5499f-979f-40bb-9687-e70e687dab69.png)

**Comment by maximthomas** [comment]
@viruls, could you please attach har log from your browser?

**Comment by viruls** [comment]
![Screen Shot 2022-10-08 at 10 51 18 AM](https://user-images.githubusercontent.com/1412321/194699051-a1cb59a7-cb4b-41f5-9a94-2fbb5ff7993c.png)

![Screen Shot 2022-10-08 at 10 51 30 AM](https://user-images.githubusercontent.com/1412321/194699053-d577a212-884b-4925-92f9-8446798cb501.png)

**Comment by viruls** [comment]
[NetworkData.xml.docx](https://github.com/OpenIdentityPlatform/OpenAM/files/9738814/NetworkData.xml.docx)

**Comment by viruls** [comment]
Found it, The issue is only happening with IE Browser. 
I don't see any issue with Chrome/Firefox. 

@maximthomas , Thanks a lot for your response. Closing this ticket now.
