### ISSUE TITLE
SAML IDP initiated SLO failing

### ISSUE THREAD

**Issue by viruls** [OpenIdentityPlatform/OpenAM#560]
Hi There,

We have two applications one is protected with a web agent and the other one is integrated with SAML.
I am able to log in to the Web application which was protected with a web agent and then SSO to SAML using an IDP-initiated SSO URL.
And then on both the web application and on SAML application, we configured a logout link which is SAML IDP Initiated SLO URL

But after clearing the session, OpenAM is not initiating the SLO SAML Request to Application and is just showing a static message "IDP initiated single logout succeeded" without also landing on the RelayState URL given in the query string. 

Please advise.

Thanks,

**Comment by viruls** [comment]
@maximthomas , could you please advise

**Comment by vharseko** [comment]
please provide logs
