### ISSUE TITLE
Can't install ssoadm Docker

### ISSUE THREAD

**Issue by anamaymane** [OpenIdentityPlatform/OpenAM#562]
Hi, I'm  facing issues when trying to install the ssoadm, when I launch the ./setup script. Once I fill all the prompted data (openam config path, ssoadm debug and log path), the script outputs the following:

/openam/boot.json

However when I verify the /openam folder, I can't find the boot.json file, and I can't either find the ssoadm binary on my docker container.

I'm using openidentityplatform/openam:14.6.6 docker image, and the setup script is located in : /usr/openam/ssoadmintools

**Comment by maximthomas** [comment]
I guess there is an issue with Docker config folder mappings and permissions. Running the OpenAM Docker image without mapping config directory to a volume and running setup command inside the container causes no issues.
```
./setup -p /usr/openam/config -d /usr/openam/ssoadmintools/debug -l /usr/openam/ssoadmintools/log --acceptLicense
amSecurity:10/15/2023 12:25:49:399 PM UTC: Thread[main,5,main]: TransactionId[unknown]
ERROR: created internalAppSSOToken:Y2FPNk5oNnJFemptTUNoZHJCUUFBZz09MTY5NzM3Mjc0OTM5Nw==, authInitialized: false, SystemProperties.isServerMode(): false,  SystemProperties.get(AMADMIN_MODE): true
The scripts are properly setup under directory: /usr/openam/ssoadmintools/openam
Debug directory is /usr/openam/ssoadmintools/debug.
Log directory is /usr/openam/ssoadmintools/log.
The version of this tools.zip is: OpenAM 14.7.3
The version of your server instance is: OpenAM 14.7.3 Build 1d3cb39d3a (2023-July-20 15:02)
```
