### ISSUE TITLE
OpenAM installation through Docker failed 

### ISSUE THREAD

**Issue by robdiluca** [OpenIdentityPlatform/OpenAM#567]
**Describe the bug**
I'm trying to install OpenAM through Docker, but an error occurs during the default configuration.

**To Reproduce**
1. Install Docker on your platform and run
`docker run -h openam-01.domain.com -p 8080:8080 --name openam-01 openidentityplatform/openam`
2. Go to `http://localhost:8080/openam`, select "Create Default Configuration" and enter the required information
3. See error
`amSecurity:12/18/2022 01:24:58:146 PM UTC: Thread[http-nio-8080-exec-9,5,main]: TransactionId[e1054c7c-f2b0-4e31-b536-ba93a70eb488-14]
Debug file can't be written : Failed to create debug directory Current Debug File : DebugFileImpl{debugDirectorynulldebugName='CoreSystem', fileCreationTime=01/01/1970 12:00:00:000 AM UTC}
amSecurity:12/18/2022 01:24:58:146 PM UTC: Thread[http-nio-8080-exec-9,5,main]: TransactionId[e1054c7c-f2b0-4e31-b536-ba93a70eb488-14]
ERROR: created internalAppSSOToken:TGh6aE1SSlhpS3pEZTU1dnJCRUFBZz09MTY3MTM2OTg5ODE0Mg==, authInitialized: false, SystemProperties.isServerMode(): true,  SystemProperties.get(AMADMIN_MODE): null
amSecurity:12/18/2022 01:24:58:151 PM UTC: Thread[http-nio-8080-exec-9,5,main]: TransactionId[e1054c7c-f2b0-4e31-b536-ba93a70eb488-14]
ERROR: created internalAppSSOToken:bTh2dXlhblNFNzdEeTBFNXJCRUFBZz09MTY3MTM2OTg5ODA2MQ==, authInitialized: false, SystemProperties.isServerMode(): true,  SystemProperties.get(AMADMIN_MODE): null
`

- Device: MacBook Air M1 2020 
- OS: BigSur
- Docker Desktop 4.3.1

Please, let me know if you need more info.

Best,
Roberto

**Comment by maximthomas** [comment]
@robdiluca hi, you need to specify OpenAM host name in the URL as [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name), so the OpenAM url should be something like `http://openam-01.domain.com:8080/openam`

the message you see is not actually an error, so you can just ignore it yet

**Comment by robdiluca** [comment]
Hi @maximthomas , thank you for your reply. I modified my /etc/hosts file in order to specify the host name in the browser, but I still obtain the same error. I would like to ignore it, but it causes the container to be stopped, so I cannot do anything else. Do you have any suggestions?

**Comment by robdiluca** [comment]
Hi @maximthomas , thank you for your reply. I modified my /etc/hosts file in order to specify the host name in the browser, but I still obtain the same error. I would like to ignore it, but it causes the container to be stopped, so I cannot do anything else. Do you have any suggestions?

**Comment by robdiluca** [comment]
Hi @maximthomas , thank you for your reply. I modified my /etc/hosts file in order to specify the host name in the browser, but I still obtain the same error. I would like to ignore it, but it causes the container to be stopped, so I cannot do anything else. Do you have any suggestions?

**Comment by maximthomas** [comment]
@robdiluca `ERROR` message should not cause shutdown of the container

**Comment by robdiluca** [comment]
@maximthomas OK, but actually something happens, because the container shutdowns after printing the log messages I have already posted. What do you suggest can I try?

**Comment by maximthomas** [comment]
@robdiluca Hi, just tried to reproduce the issue with the latest OpenAM docker image. And everything seems to be ok. 
Please check your container engine logs. May be there is an info to find the shutdown cause.

**Comment by robdiluca** [comment]
@maximthomas hi, I've downloaded the latest image and it seems to work now. Thank you for your support.
