### ISSUE TITLE
Error running OIDC Script 

### ISSUE THREAD

**Issue by dairoca90** [OpenIdentityPlatform/OpenAM#585]
**Describe the bug**
Cannot consume userinfo without adding Script1 tag to the OIDC Claims Java Class White List 

**To Reproduce**
1. Configure OAuth2 Provider
2. Create OAuth2 Client for OpenID
3. Do the Authorize Flow
4. Retrieve access token  
5. See error when trying to use userInfo endpoint

**Expected behavior**
Retrive user info data
**Screenshots**
<img width="1511" alt="Captura de pantalla 2023-02-18 a la(s) 14 24 11" src="https://user-images.githubusercontent.com/38822740/219894767-1286eb56-90b2-466c-b13a-fc91ba3aa773.png">
<img width="1449" alt="Captura de pantalla 2023-02-18 a la(s) 14 25 03" src="https://user-images.githubusercontent.com/38822740/219894768-28c0223b-7659-4d0d-a55a-47ca1ed350a6.png">

**Desktop (please complete the following information):**
 - OS: ventura 13.1
 - Browser [safari,chrome,firefox, curl, postmancanary]

**Additional context**
Every time the logs are deleted a new consecutive Script2 tag is required

**Comment by maximthomas** [comment]
@dairoca90 
Open OpenAM console, then go to **Configure -> Global Services -> Scripting -> Secondary Configurations -> OIDC_CLAIMS -> Secondary Configurations -> EngineConfiguration** and add to **Java class whitelist** setting all necessary Java classes
