### ISSUE TITLE
No Grant Type option for OAuth 2.0 Provider

### ISSUE THREAD

**Issue by spyhunter88** [OpenIdentityPlatform/OpenAM#596]
**Describe the bug**
I try to use nestjs client with OpenAM 14 (run from docker with latest 14.7.2). I already create new Realm, create OAuth 2.0/OpenID Connect client. User/subject is already created.
I try nestjs-oauth2 package then it seem work but get "grant_type is not set" when getAccessToken step.

**To Reproduce**
1. Go to login route in nestjs, then redirect to OpenAM login.
2. Provide user and password.
3. It back to nestjs callback page to getAccessToken then get error: `grant_type is not set`.
4. See error.

**Expected behavior**
Login and get accesstoken from OpenAM. Or atleast by pass the `grant_type is not set` error.

**Additional context**
I find many instruction from ForgeRock, all lead to "add Grant Type in Advanced tab ..." but I never find it, my OpenAM use legacy UI but no Grant Type option between Response Type and Contacts (I see a few image and it should be there).
Other setting:
```
Client Type: test both Confidential and Public.
Scope: openid, profile, fr:idm:profile, fr:idm:notifications, fr:idm:consent_read.
Claims: <empty>
Display name: <empty>
Display description: <empty>
Default scopes: <empty>
Response Type: code
Contact: empty
Token Endpoint Authentication Method: client_secret_basic.
Other leaves default.
```

I already check the source code of `nestjs-oauth2`, it still set the `grant_type: 'authorization_code'`

**Comment by vharseko** [comment]
please provide har log

**Comment by spyhunter88** [comment]
Sorry, please closed this issue. I could not resolve it and changed to Keycloak, but now I not in this project anymore.
