### ISSUE TITLE
What is the relationship between this repo and forgerock openam ?

### ISSUE THREAD

**Issue by vricosti** [OpenIdentityPlatform/OpenAM#603]
Hi,
I have an old project using forgerock openam and I would like to understand the relationship/history with forgerock openam that don't seem to be maintained.
Can I use this project instead ?

Thanks

**Comment by maximthomas** [comment]
Hi @vricosti,
This project and ForgeRock OpenAM have the same origin. You can read more history details here https://en.wikipedia.org/wiki/OpenAM

And sure, you can use this project instead.
