### ISSUE TITLE
seems there are some words missing in the document

### ISSUE THREAD

**Issue by lc275** [OpenIdentityPlatform/OpenAM#628]
below is sinppets from the [document,](https://github.com/OpenIdentityPlatform/OpenAM/wiki/Quick-Start-Guide) seems there are some words missing 
Prepare Hosts File
At first you need to add your ( **words missing here** ) to your hosts file aliases openam.example.com - for OpenAm and example.com for Apache Http Server. Your hosts file should contain following line:

**Comment by maximthomas** [comment]
@lc275 thank you for the issue!
Fixed misspelling. please, [check](https://github.com/OpenIdentityPlatform/OpenAM/wiki/Quick-Start-Guide)
