### ISSUE TITLE
Error in Setup & Test WebAuthn support locally on Window 10

### ISSUE THREAD

**Issue by amitt0488** [OpenIdentityPlatform/OpenAM#642]
I need to setup openAM locally on window 10 laptop and then want to test WebAuthn.
- For this, I am following this repo to start OpenAM and OpenDJ in Separate Docker Containers
https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-Start-OpenAM-and-OpenDJ-in-Separate-Docker-Contaners
they are running fine and i am able to login into openam console.

- Now, for setting up webauthn, i followed this article
https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-Setup-WebAuthn-Authentication-in-OpenAM

Now I am getting an error while Testing WebAuthn Registration Authentication Chain.

![image](https://github.com/OpenIdentityPlatform/OpenAM/assets/25524694/c9377647-88ba-4c68-9a6e-6ba9c5c57857)

May be I need to setup this on HTTPS ? Could this be the reason (currently openAM is running on HTTP) ?

**Comment by maximthomas** [comment]
WebAuthn only works in classic UI (enabled with `XUI.enable=false` system property). There is an important note in the [wiki](https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-Setup-WebAuthn-Authentication-in-OpenAM#notes). 
Seems you are using XUI for authentication. You should use classic UI, so authentication URL should look like this:
https://openam.example.com:8443/openam/UI/Login?org=/users&service=webauthn-registration
