### ISSUE TITLE
Unable to create users realm in openAM setup

### ISSUE THREAD

**Issue by amitt0488** [OpenIdentityPlatform/OpenAM#643]
I want to test webauthn functionality in openAM and following this article
https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-Setup-WebAuthn-Authentication-in-OpenAM#setting-up-authentication-modules 

As per this article, there has to be a /users realm. When I try to create this realm. It gives me error:

"Organization name users is invalid"

1. Can i do this in any other realm or under Top level realm?

2. Also, for testing webauthn, is it necessary that openAM should work under HTTPS?

![image](https://github.com/OpenIdentityPlatform/OpenAM/assets/25524694/872232db-3af9-4ac8-9252-cd053f9d28d2)

**Comment by maximthomas** [comment]
@amitt0488 Hi, `users` keyword is reserved, try a different realm name. For example `clients` or `staff`

**Comment by maximthomas** [comment]
@amitt0488 There is an issue in the documentation, you should use a different realm name, because `users` is reserved. I have just changed realm name to `clients` in the wiki page.

**Comment by maximthomas** [comment]
> Also, for testing webauthn, is it necessary that openAM should work under HTTPS?

You can use either https or `localhost` hostname with http
