### ISSUE TITLE
An internal authentication error has occurred while testing webAuthn

### ISSUE THREAD

**Issue by amitt0488** [OpenIdentityPlatform/OpenAM#644]
I have setup openAM and openDJ on my window 10 laptop referring this https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-Start-OpenAM-and-OpenDJ-in-Separate-Docker-Contaners 

During the setup, I specified openAM hostname as localhost.
Also, after the setup I disabled XUI

![image](https://github.com/OpenIdentityPlatform/OpenAM/assets/25524694/b0ee820d-a312-40a7-b8f9-a374218615ce)

![image](https://github.com/OpenIdentityPlatform/OpenAM/assets/25524694/487b14e6-a9f5-4cfe-bc2e-0dc86d322a49)

After all this, I followed this article for setting up webauthn module https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-Setup-WebAuthn-Authentication-in-OpenAM 

But, now when I try to hit this URL http://localhost:8080/openam/UI/Login?org=/clients&service=webauthn-registration 
, it takes me to an error page saying "An internal authentication has occurred"

Please help me in this.

![image](https://github.com/OpenIdentityPlatform/OpenAM/assets/25524694/1a7cda41-f99a-40a0-ba0a-362e0c33f17b)

**Comment by maximthomas** [comment]
I can't reproduce the issue in the local environment. Just run the latest OpenAM docker image, set up classic UI, WebAuthN authentication module and chain and don't see any issue. Please attach `<openam config folder>/openam/debug` and `<openam config folder>/openam/log` folders contents for analysis.

**Comment by amitt0488** [comment]
[openam-folders.zip](https://github.com/OpenIdentityPlatform/OpenAM/files/12749335/openam-folders.zip)
I have used the latest openam docker image and have done all the settings as specified in this repo.
Attaching the openam config, debug & log folder.

And this is docker-compose file:



**version: '3.9'

services:
  openam:
    image: openidentityplatform/openam:latest
    ports:
      - "8080:8080"
    hostname: localhost
    volumes:
      - ./persistence/openam:/usr/openam/config

  opendj:
    image: openidentityplatform/opendj:latest
    hostname: opendj.example.com
    ports:
      - "1389:1389"
      - "1636:1636"
      - "4444:4444"
    volumes:
      - ./opendj/bootstrap/data/:/opt/opendj/bootstrap/data
      - ./opendj/bootstrap/schema/:/opt/opendj/bootstrap/schema
      - ./persistence/opendj:/opt/opendj/data
    environment:
      - BASE_DN=dc=openam,dc=openidentityplatform,dc=org**

**Comment by amitt0488** [comment]
But, With webauthn-authentication, on hitting this url, (http://localhost:8080/openam/UI/Login?org=/clients&service=webauthn-authentication)  i get this page:

![image](https://github.com/OpenIdentityPlatform/OpenAM/assets/25524694/8ea0479d-c2a9-4574-a9fa-35c391eced4b)

I created this user in openDJ:
testuser

![image](https://github.com/OpenIdentityPlatform/OpenAM/assets/25524694/07c580b1-80e8-4a92-9d1e-e82369ee7121)

But, when I click on login button, I get authentication failed error

![image](https://github.com/OpenIdentityPlatform/OpenAM/assets/25524694/737ef682-5c08-4409-a7ef-bafdf7c0c8a8)

My openam setting looks like this:

![image](https://github.com/OpenIdentityPlatform/OpenAM/assets/25524694/3103b50d-4934-4488-99f2-be534c75e421)

**Comment by amitt0488** [comment]
Now the registration and authentication pages are showing up correctly.
I redeployed it and  I guess i set the webauthn-authentication chain criteria to 'required' instead of 'requisite'

Thanks for your support.

**Comment by amitt0488** [comment]
Just one more question:
For testing the end to end flow, is there an emulator for Windows as well, just like linux and Mac?
or is there any other way by which this can be tested?

**Comment by maximthomas** [comment]
Glad I could help
There is an [WebAuthn emulator](https://developer.chrome.com/docs/devtools/webauthn/) in Chrome Browser
