### ISSUE TITLE
Saving Policy settings partially work

### ISSUE THREAD

**Issue by pentike** [OpenIdentityPlatform/OpenAM#69]
**Describe the bug**
Hi,

I have just tried the docker image with OpenAM 14.1.6 Build 99655c8cac (2018-July-24 15:42). If I go to the Subject tab of a Policy, I instantly get a 
"The "Not..." logical operator can only accept one child"
info message however the "All of..." item is selected. If I alter the configuration in any way and click Save changes, the page jumps back to the Resources tab and the changes are lost.
If I save the changes on any other tab, I also have to refresh the browser to get the settings back.

**To Reproduce**
1. Go to 'Authorization->Policy sets->Default policy set->Test policy'
2. Click on 'Save changes'

**Expected behavior**
The settings are saved.

**Screenshots**
![1-policy-settings-before-saved](https://user-images.githubusercontent.com/3485076/43643401-799f0544-972b-11e8-8aba-492fd593480b.png)
![2-policy-settings-after-save](https://user-images.githubusercontent.com/3485076/43643402-79bece60-972b-11e8-9491-6cd9e95ff57c.png)
![3-policy-settings-after-reload](https://user-images.githubusercontent.com/3485076/43643403-79dce3fa-972b-11e8-9243-47f2144f41dc.png)
![4-policy-subjects-after-reload](https://user-images.githubusercontent.com/3485076/43643404-79faaa70-972b-11e8-8064-00592fc6d7d3.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu
 - Browser Firefox 61.0.1

Regards,
Gábor

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/14.1.7
