### ISSUE TITLE
Tomcat deployment start failed

### ISSUE THREAD

**Issue by paalgyula** [OpenIdentityPlatform/OpenAM#7]
I've got the following exception from OpenAM 14.0.6 WAR deployment from Tomcat 8.5:

```
23-Apr-2018 06:24:24.276 INFO [localhost-startStop-2] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/var/lib/tomcat8/webapps/OpenAM-14.0.6.war]
23-Apr-2018 06:24:40.478 INFO [localhost-startStop-2] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
23-Apr-2018 06:24:40.950 SEVERE [localhost-startStop-2] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start:
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/OpenAM-14.0.6]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1856)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.sun.istack.localization.LocalizableMessageFactory.<init>(Ljava/lang/String;Lcom/sun/istack/localization/LocalizableMessageFactory$ResourceBundleSupplier;)V
	at com.sun.xml.ws.resources.WsservletMessages.<clinit>(WsservletMessages.java:59)
	at com.sun.xml.ws.transport.http.servlet.WSServletContextListener.parseAdaptersAndCreateDelegate(WSServletContextListener.java:139)
	at com.sun.xml.ws.transport.http.servlet.WSServletContainerInitializer.onStartup(WSServletContainerInitializer.java:65)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5229)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more
```

**Comment by vharseko** [comment]
can not reproduce on tomcat-8.0.51 

23-Apr-2018 15:55:25.200 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/tmp/apache-tomcat-8.0.51/temp
23-Apr-2018 15:55:25.200 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /Users/vharseko/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
23-Apr-2018 15:55:25.342 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
23-Apr-2018 15:55:25.373 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
23-Apr-2018 15:55:25.375 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
23-Apr-2018 15:55:25.377 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
23-Apr-2018 15:55:25.377 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 536 ms
23-Apr-2018 15:55:25.399 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
23-Apr-2018 15:55:25.399 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.51
23-Apr-2018 15:55:25.419 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /private/tmp/apache-tomcat-8.0.51/webapps/OpenAM-14.0.7-SNAPSHOT.war
23-Apr-2018 15:55:38.664 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
23-Apr-2018 15:55:40.230 INFO [localhost-startStop-1] com.sun.xml.ws.transport.http.servlet.WSServletDelegate.<init> WSSERVLET14: JAX-WS servlet initializing
FAMClassLoader : found new Metro class in global classpath
23-Apr-2018 15:55:42.541 INFO [localhost-startStop-1] com.sun.xml.ws.transport.http.servlet.WSServletContextListener.contextInitialized WSSERVLET12: JAX-WS context listener initializing
23-Apr-2018 15:55:42.541 INFO [localhost-startStop-1] com.sun.xml.ws.transport.http.servlet.WSServletContextListener.contextInitialized WSSERVLET12: JAX-WS context listener initializing
Starting up OpenAM at Apr 23, 2018 3:55:42 PM
FAMClassLoader : found new Metro class in global classpath
23-Apr-2018 15:55:42.671 INFO [localhost-startStop-1] com.sun.jersey.server.impl.application.WebApplicationImpl.initiate Initiating Jersey application, version 'Jersey: 1.1.1-ea 07/14/2009 07:18 PM'
23-Apr-2018 15:55:43.128 INFO [localhost-startStop-1] com.sun.jersey.server.impl.application.WebApplicationImpl.initiate Initiating Jersey application, version 'Jersey: 1.1.1-ea 07/14/2009 07:18 PM'
23-Apr-2018 15:55:47.433 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /private/tmp/apache-tomcat-8.0.51/webapps/OpenAM-14.0.7-SNAPSHOT.war has finished in 22,013 ms
23-Apr-2018 15:55:47.436 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /private/tmp/apache-tomcat-8.0.51/webapps/docs
23-Apr-2018 15:55:47.454 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /private/tmp/apache-tomcat-8.0.51/webapps/docs has finished in 18 ms
23-Apr-2018 15:55:47.454 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /private/tmp/apache-tomcat-8.0.51/webapps/examples
23-Apr-2018 15:55:47.722 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /private/tmp/apache-tomcat-8.0.51/webapps/examples has finished in 268 ms
23-Apr-2018 15:55:47.723 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /private/tmp/apache-tomcat-8.0.51/webapps/host-manager
23-Apr-2018 15:55:47.769 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /private/tmp/apache-tomcat-8.0.51/webapps/host-manager has finished in 47 ms
23-Apr-2018 15:55:47.769 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /private/tmp/apache-tomcat-8.0.51/webapps/manager
23-Apr-2018 15:55:47.793 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /private/tmp/apache-tomcat-8.0.51/webapps/manager has finished in 24 ms
23-Apr-2018 15:55:47.793 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /private/tmp/apache-tomcat-8.0.51/webapps/ROOT
23-Apr-2018 15:55:47.806 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /private/tmp/apache-tomcat-8.0.51/webapps/ROOT has finished in 13 ms
23-Apr-2018 15:55:47.810 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
23-Apr-2018 15:55:47.820 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
23-Apr-2018 15:55:47.824 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 22447 ms

**Comment by vharseko** [comment]
try 

``
mkdir $CATALINA_HOME/endorsed
``
``
cp $CATALINA_HOME/endorsed/webapps/OpenAM-14.0.6/WEB-INF/lib/wsit-*.jar 
$CATALINA_HOME/endorsed
``
``
cp $CATALINA_HOME/endorsed/webapps/OpenAM-14.0.6/WEB-INF/lib/jaxb-*.jar $CATALINA_HOME/endorsed
``

**Comment by paalgyula** [comment]
Yes you were right, sorry about my tomcat instance had a different libraries...

**Comment by vharseko** [comment]
Thank for feedback
