### ISSUE TITLE
AD as Datastore, On Authentication failure Show the corresponding error message (Password Expired, User Inactive)

### ISSUE THREAD

**Issue by viruls** [OpenIdentityPlatform/OpenAM#71]
Dear Folks,

I am trying to login with inactive user or with a user whose password is expired ,I am seeing Authentication failed error message (Using Legacy UI) where as I am expecting the corresponding error message.

Note: AD is our Datastore.

Please advise how to achieve this.

Thanks,
Narendra

**Comment by vharseko** [comment]
please attach screenshots with 

- auth module settings
- datastore settings

and logs with debug mode

**Comment by viruls** [comment]
[Screenshots.zip](https://github.com/OpenIdentityPlatform/OpenAM/files/2269221/Screenshots.zip)

**Comment by vharseko** [comment]
please attach screenshots with
- ldapService chain settings
- auth module settings in chain ldapService
and logs with debug mode

**Comment by viruls** [comment]
Hi Vharseko,

Thanks for your prompt response, unfortunately we don't have debug logs at this moment as not enabled. Besides attaching the ldapservice chain settings.

![ldapservice](https://user-images.githubusercontent.com/1412321/43828135-3721b0c0-9b2e-11e8-9142-bf6d23e6d36b.PNG)

Thanks,

**Comment by vharseko** [comment]
cannot reproduce without logs
