### ISSUE TITLE
About OAuth2.0  Redirection URIs "?" mark

### ISSUE THREAD

**Issue by nervermore1** [OpenIdentityPlatform/OpenAM#714]
### Discussed in https://github.com/OpenIdentityPlatform/OpenAM/discussions/713

<div type='discussions-op-text'>

<sup>Originally posted by **nervermore1** January 23, 2024</sup>
My uri format is like this:
https://host:port/path?client=test
When I use OAuth2 to log in,there is a error 'redirect_uri_mismatch The redirection URI provided does not match a pre-registered value.'</div>

**Comment by vharseko** [comment]
not issue

**Comment by nervermore1** [comment]
Hi,
How to fill in the Redirection URIs value?I do not make it work yet.
Thank u.

**Comment by vharseko** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by nervermore1** [comment]
Describe the bug
Today i use the OpenAM OAuth2.0 service to obtain the access token ,I am encountering this error:
`    "error_description": "The provided access grant is invalid, expired, or revoked.",
    "error": "invalid_grant"`

To Reproduce
Steps to reproduce the behavior:
  1.Start OAuth2 Provider with default configuration
  2.Click /Applications/OAuth2.0 and create a new agent.Redirection URIs is **https://192.168.0.1/login**
  3.The redirection uri in Authorization Request is **https://192.168.0.1/login?idp_id=1**
  4.Client requests an access token with redirection uri  **https://192.168.0.1/login?idp_id=1**
  5.OpenAM respones the error **invalid_grant**

Desktop (please complete the following information):
OS: CentOS7
Browser Chrome
Version 14.8.2

**Comment by vharseko** [comment]
https://192.168.0.1/login != https://192.168.0.1/login?idp_id=1

**Comment by nervermore1** [comment]
`com.forgerock.openam.oauth2provider.accessTokenLifeTime=0
com.forgerock.openam.oauth2provider.authorizationCodeLifeTime=0
com.forgerock.openam.oauth2provider.claims[0]=Claims
com.forgerock.openam.oauth2provider.clientName[0]=
com.forgerock.openam.oauth2provider.clientType=Confidential
com.forgerock.openam.oauth2provider.contacts[0]=zhu.chenjie@zte.com.cn
com.forgerock.openam.oauth2provider.defaultMaxAge=600
com.forgerock.openam.oauth2provider.defaultMaxAgeEnabled=false
com.forgerock.openam.oauth2provider.defaultScopes[0]=postaladdress
com.forgerock.openam.oauth2provider.description[0]=---集成方案
com.forgerock.openam.oauth2provider.idTokenSignedResponseAlg=HS256
com.forgerock.openam.oauth2provider.jwksURI=http://197.20.27.102:8080/openam/oauth2/connect/jwk_uri
com.forgerock.openam.oauth2provider.jwtTokenLifeTime=0
com.forgerock.openam.oauth2provider.name[0]=水平云单点认证
com.forgerock.openam.oauth2provider.postLogoutRedirectURI[0]=
com.forgerock.openam.oauth2provider.publicKeyLocation=jwks_uri
com.forgerock.openam.oauth2provider.redirectionURIs[0]=https://192.168.0.1/login?idp_id=1
com.forgerock.openam.oauth2provider.refreshTokenLifeTime=0
com.forgerock.openam.oauth2provider.responseTypes[0]=code
com.forgerock.openam.oauth2provider.responseTypes[1]=token
com.forgerock.openam.oauth2provider.responseTypes[2]=id_token
com.forgerock.openam.oauth2provider.responseTypes[3]=code token
com.forgerock.openam.oauth2provider.responseTypes[4]=token id_token
com.forgerock.openam.oauth2provider.responseTypes[5]=code id_token
com.forgerock.openam.oauth2provider.responseTypes[6]=code token id_token
com.forgerock.openam.oauth2provider.scopes[0]=postaladdress
com.forgerock.openam.oauth2provider.subjectType=Public
com.forgerock.openam.oauth2provider.tokenEndPointAuthMethod=client_secret_basic
idTokenEncryptionAlgorithm=RSA1_5
idTokenEncryptionEnabled=false
idTokenEncryptionMethod=A128CBC-HS256
isConsentImplied=false
sunIdentityServerDeviceStatus=Active`
![Snipaste_2024-01-24_18-56-58](https://github.com/OpenIdentityPlatform/OpenAM/assets/156501924/05e3fc03-3bc9-4421-9503-1853b21f71ef)

**Comment by nervermore1** [comment]
I have tried using  Redirection URIs **https://192.168.0.1/login?idp_id=1** 
`com.forgerock.openam.oauth2provider.redirectionURIs[0]=https://192.168.0.1/login?idp_id=1`
I  encountered this error:
`redirect_uri_mismatch The redirection URI provided does not match a pre-registered value.`

**Comment by vharseko** [comment]
check 
com.forgerock.openam.oauth2provider.redirectionURIs[0]=https://192.168.0.1/login
com.forgerock.openam.oauth2provider.redirectionURIs[1]=https://192.168.0.1/login?idp_id=1

**Comment by nervermore1** [comment]
```
com.forgerock.openam.oauth2provider.redirectionURIs[0]=https://192.168.0.1/login
com.forgerock.openam.oauth2provider.redirectionURIs[1]=https://192.168.0.1/login?idp_id=1
```
or
```
com.forgerock.openam.oauth2provider.redirectionURIs[0]=https://192.168.0.1/login?idp_id=1
com.forgerock.openam.oauth2provider.redirectionURIs[1]=https://192.168.0.1/login
```
Redirect successful,but
When Client requests an access token with redirection uri https://192.168.0.1/login?idp_id=1,OpenAM respones the error invalid_grant
