### ISSUE TITLE
Building web policy agent from quistart  guide is not working

### ISSUE THREAD

**Issue by fjbeli** [OpenIdentityPlatform/OpenAM#728]
Hi, following the quick start guide, the docker file used to build the image of policy agent ends up with these issues :

` > [ 3/10] RUN apt-get install -y wget unzip:
0.098 Reading package lists...
0.109 Building dependency tree...
0.109 Reading state information...
0.110 E: Unable to locate package wget
0.110 E: Unable to locate package unzip
`
Tried with new images would result to incompatibilty of Openssl.

Thanks

**Comment by maximthomas** [comment]
@fjbeli I've just fixed the guide, please check https://github.com/OpenIdentityPlatform/OpenAM/wiki/Quick-Start-Guide#apache-http-server-configuration

**Comment by fjbeli** [comment]
@maximthomas  first issue was solved. however another issue encountered at the last step of installing the agent:
cat the server log : 
`2024-03-10 13:40:21  am_agent_login(): error -14 (no route to host) connecting to http://openam.example.com:8080/openam`
however if I skip that step during the build and bash into the container I could install it.
Would it be possible to follow the quickstart and make sure if you have all worked.

**Comment by fjbeli** [comment]
ok I managed to solve the issue by adding:
`--add-host=openam.example.com:172.17.0.2` 
to the build command.
It is strange that this quick guide was tested successfully :/. or I may be was not tested at all?

**Comment by maximthomas** [comment]
@fjbeli hi, I've updated the guide, moved to Docker network to setup connection between containers. Docker `--link` argument became obsolete.
