### ISSUE TITLE
Due to dependency of xmlsec-2.1.7 in the openam-federationCaused by: java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by sasi29** [OpenIdentityPlatform/OpenAM#730]
In the openam-federation-library, the xmlsec code is not updated from the old version to the latest one cause of the changes made by this jira ticket https://issues.apache.org/jira/browse/SANTUARIO-377, getting abstractmethod error. when the xmlsignature.sign method is called at at com.sun.identity.saml2.xmlsig.FMSigProvider.sign(FMSigProvider.java:220)

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/15.0.0
