### ISSUE TITLE
Integration with Biometric APIs

### ISSUE THREAD

**Issue by dpat061** [OpenIdentityPlatform/OpenAM#737]
It is pretty frustrating to remember all the passwords to various accounts. A simpler and more secure solution can be biometric authentication through fingerprint or face IDs. 

By integrating biometric authentication APIs within OpenAM, developers can incorporate methods like fingerprint scanning, facial recognition, and/or iris scanning which can help make the software more accessible.

If no appropriate APIs are found, third-party biometric authentication services can be a good starting point. They of course cannot be considered long-term solutions considering potential privacy concerns.

**Comment by maximthomas** [comment]
Hi @dpat061 
OpenAM have WebAuthN auhentication, so you can use biometric or hardware tokens for authentication. You can use https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-Setup-WebAuthn-Authentication-in-OpenAM article as a starting point.
