### ISSUE TITLE
Issue creating OpenAM install from config file

### ISSUE THREAD

**Issue by FireBurn** [OpenIdentityPlatform/OpenAM#753]
05/23/2024 11:05:43:663 am BST: Loading Schema /apps/was/openam/odsee_pushdevices.ldif
05/23/2024 11:05:43:670 am BST: ...Success.
Configuration Failed.  The server returned error code :500

AMSetupServlet.processRequest: errororg.forgerock.i18n.LocalizedIllegalArgumentException: The provided value "ou=,ou=default,ou=OrganizationConfig,ou=1.0,ou=sunIdentityRepositoryService,ou=services,dc=openam,dc=openidentityplatform,dc=org" cou
ld not be parsed as a valid distinguished name because an attribute value started with a character at position 3 that needs to be escaped

[sanatisedConfig.txt](https://github.com/OpenIdentityPlatform/OpenAM/files/15415438/sanatisedConfig.txt)

If I create from the WebGUI it creates just fine

**Comment by maximthomas** [comment]
Hi @FireBurn 
If you are using the embedded datastore, you can just comment the `USERSTORE_TYPE` options, so other `USERSTORE_*` options will be ignored. If you have to set up user DS to a remote OpenDJ instance, you should set `USERSTORE_TYPE=LDAPv3ForOpenDS`

**Comment by FireBurn** [comment]
Perfect, that got things working
