### ISSUE TITLE
Logging on with XUI gives User name/password combination is invalid.

### ISSUE THREAD

**Issue by FireBurn** [OpenIdentityPlatform/OpenAM#755]
Logon with legacy UI, click "Switch to XUI" this takes you to a login screen where the same credentials gives the error: 

User name/password combination is invalid.

I can see ffdc's complaining about missing files:

/XUI/css/bootstrap.css.map
/XUI/libs/base64.min.js.map
/XUI/locales/en-GB/translation.json

should those be:

/XUI/css/bootstrap-3.3.5-custom.css
/XUI/libs/base64-1.0.0-min.js
/XUI/locales/en/translation.json

**Comment by maximthomas** [comment]
Have you set up httponly cooke? In this case XUI unfortunately won't work.
These missing files do not cause any functional bugs.

**Comment by FireBurn** [comment]
I do indeed, thanks
