### ISSUE TITLE
Creating default configuration fails with fatal error: cannot obtain application SSO token

### ISSUE THREAD

**Issue by k2aj** [OpenIdentityPlatform/OpenAM#756]
**Describe the bug**
I'm trying to run OpenAM 15.0.0 using the official container image and instructions from Docker Hub. Attempting to create a default configuration fails with the error message:

```
AdminTokenAction: FATAL ERROR: Cannot obtain Application SSO token., refer to install.log under /usr/openam/config for more information.
```

I've attached the mentioned [install.log](https://github.com/OpenIdentityPlatform/OpenAM/files/15451853/install.log) file.

**To Reproduce**
1. Add `openam-01.domain.com` to the hosts file.
2. Run the docker container: `docker run -h openam-01.domain.com -p 8080:8080 --name openam-01 openidentityplatform/openam:15.0.0`.
3. Open `openam-01.domain.com/openam` in your browser.
4. Click `Create default Configuration`
5. Fill passwords in the popup and click `Create Configuration`
6. It fails with the message `AdminTokenAction: FATAL ERROR: Cannot obtain Application SSO token., refer to install.log under /usr/openam/config for more information.`

**Expected behavior**
Creating the default configuration succeeds.

**Desktop (please complete the following information):**
 - OS: EndeavourOS Linux (kernel 6.9.1-arch1-2)
 - Browser: Chromium 125.0.6422.112-1
- Docker version: 26.1.3, build b72abbb6f0

**Comment by maximthomas** [comment]
Hello,

Run the OpenAM setup process again with the debug mode enabled using the following command:

```bash
docker run -h openam.example.org -p 8080:8080 --network openam --name openam openidentityplatform/openam:15.0.0 \
 "sh" "-c" "CATALINA_OPTS=\"\$CATALINA_OPTS -Dcom.iplanet.services.debug.level=message\" && /usr/local/tomcat/bin/catalina.sh run"
```

Then attach the log files from the docker `/usr/openam/config/openam/debug` directory. I guess it could help to diagnose the cause of the problem
