### ISSUE TITLE
LDAP Authentication Page not fully translated in en_GB

### ISSUE THREAD

**Issue by FireBurn** [OpenIdentityPlatform/OpenAM#760]
This is with the locale "en_GB"

Authentication -> LDAP Module Instance

<img width="638" alt="Screenshot 2024-06-11 at 13 32 48" src="https://github.com/OpenIdentityPlatform/OpenAM/assets/86515/2e6b86cb-9f7f-4d5d-bee7-21b1dfc872db">

**Comment by maximthomas** [comment]
@FireBurn Hi,
I can't reproduce the issue. Changed the platform locale to en_GB, and changed browser Accept-Headers to en_GB as well. There is no issue. There are no resources for en_GB for the LDAP module: https://github.com/OpenIdentityPlatform/OpenAM/tree/15.0.0/openam-authentication/openam-auth-ldap/src/main/resources. So OpenAM uses the default locale
