### ISSUE TITLE
OAuth2 realm config - updating 'scopes supported' requires a restart

### ISSUE THREAD

**Issue by lscorcia** [OpenIdentityPlatform/OpenAM#790]
**Describe the bug**
Hi, very small issue here. When editing the "scopes supported" field in the OAuth2 realm config, a server restart is required to make sure the scopes are updated in the metadata endpoint. It should be possible to update those at runtime.

**To Reproduce**
1. Go to Services > OAuth2 Provider
2. Click on Supported Scopes, add a new scope
3. Visit the metadata endpoint https://yourhost/openam/oauth2/realms/root/.well-known/openid-configuration
4. See the new scope is missing.
5. Restart the webapp
6. Visit the metadata endpoint, see that the new scope is now present.

**Expected behavior**
The new scope should be immediately visible.

**Screenshots**
![immagine](https://github.com/user-attachments/assets/43175bbe-21a8-4a81-8b66-3201939fa5f0)

**Additional context**
It seems that the issue was already fixed in the other fork openam-jp: https://github.com/openam-jp/openam/pull/155/files .
The fix should be applicable to this project too by applying the same change here:

https://github.com/OpenIdentityPlatform/OpenAM/blob/48357235bd38c0019b4432215d9fdfd83fcc6da3/openam-oauth2/src/main/java/org/forgerock/oauth2/core/RealmOAuth2ProviderSettings.java#L1036-L1038

**Comment by vharseko** [comment]
please check artifacts from https://github.com/OpenIdentityPlatform/OpenAM/actions/runs/10936877974
