### ISSUE TITLE
Some openam REST APIs return 500 error code when upgraded from an older version

### ISSUE THREAD

**Issue by pdaterao** [OpenIdentityPlatform/OpenAM#795]
**Describe the bug**

REST APIs returning a list of objects return a 500 error code with the following message instead.

```
Can not start an object, expecting field name (context: Object)
```

The same APIs work if it is a fresh configuration.

APIs that fail with 500 error code:
```
{{baseurl}}/groups?_queryFilter=true
{{baseurl}}/users?_queryFilter=true
```

**To Reproduce**
1. Upgrade openam to 13.0.0 from version 10.0.0
2. Upgrade openam to 14.x from version 13.0.0
3. Call the above mentioned APIs

**Expected behavior**
Return list of objects (users or groups)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Browser: chrome
 - Version: OpenAM 14.7.4

**Additional context**
None

**Comment by vharseko** [comment]
Please provide 
* full request/response dump with curl or har
* attach logs

**Comment by pdaterao** [comment]
[openam_rest_errors.har.zip](https://github.com/user-attachments/files/17119664/openam_rest_errors.har.zip)
Attached the HAR file.

No relevant errors were observed in the los under $CONFIG_DIR/openam/{debug,log}
Are you looking for any specific file. Please let me know.

**Comment by vharseko** [comment]
try [How to make OpenAM log more verbose](https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-make-OpenAM-log-more-verbose) or attach zip for reproduce

**Comment by pdaterao** [comment]
[logs.zip]
See attached.

**Comment by vharseko** [comment]
```
Caused by: java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:104)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:621)
	at org.glassfish.grizzly.nio.transport.TCPNIOConnectorHandler.connectAsync(TCPNIOConnectorHandler.java:137)
```
please check **sun-idrepo-ldapv3-config-ldap-server=oak-vcs643** ... settings or remove this datastore

**Comment by pdaterao** [comment]
Removed the datastore. Still observing the issue. See attached logs.
[logs.zip]

**Comment by vharseko** [comment]
check Configuration -> Global -> REST APIs -> Default Version: Latest
<img width="656" alt="Снимок экрана 2024-09-26 в 20 07 13" src="https://github.com/user-attachments/assets/dbbd060b-b51f-4183-ad89-96a97ba75ffc">
