### ISSUE TITLE
OpenAM releases depending on OpenDJ releases

### ISSUE THREAD

**Issue by FireBurn** [OpenIdentityPlatform/OpenAM#8]
Hi

Just wondering if OpenAM releases should be depending on OpenDJ releases rather than snapshots

Obviously there's not much difference between the two unless a lot of development has happened

Cheers

Mike

**Comment by vharseko** [comment]
you are right, you need to fix it

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenAM/pull/14/commits/e32f09d5de103e91b0715fc6480835ff52d61b76
