### ISSUE TITLE
Missing OpenAM Java SDK API Specification in the documentation

### ISSUE THREAD

**Issue by korah91** [OpenIdentityPlatform/OpenAM#810]
**Describe the bug**
In the [Developing Client Applications](https://doc.openidentityplatform.org/openam/dev-guide/chap-client-dev) part of the documentation, if I click the [OpenAM Java SDK API Specification](https://doc.openidentityplatform.org/openam/apidocs) link it shows me a Page Not Found error

**To Reproduce**
1. Go to [Developing Client Applications](https://doc.openidentityplatform.org/openam/dev-guide/chap-client-dev#install-sdk-samples)
2. Click on OpenAM Java SDK API Specification
3. See Page Not Found error

**Expected behavior**
It should show the Java SDK API Specification, as I suppose there should be one

Thanks for all the hard work in this project :)

**Comment by maximthomas** [comment]
Fixed the missing link. 
@korah91 please check.

**Comment by korah91** [comment]
It works perfectly, thanks for the change!
