### ISSUE TITLE
Docker Image - Missing Default Ports for Embedded OpenDJ

### ISSUE THREAD

**Issue by joelcharlebois** [OpenIdentityPlatform/OpenAM#826]
The Docker Image for OpenAM posted to Docker Hub, I am assuming by the OpenIdentityPlatform team, is missing default ports for the Embedded OpenDJ instance.

Creating a Default Configuration fails during the OpenDJ setup stage, because all of the required ports are set as minus one "-1".

The same can be seen when Creating a New Configuration, except there the user can set the ports.  

Screenshots attached.   

![Screenshot 2024-12-19 164021](https://github.com/user-attachments/assets/663b2821-bc40-45be-b5af-49295b6e9b13)
 

![Screenshot 2024-12-19 164436](https://github.com/user-attachments/assets/01a29856-b1ac-4572-9798-dd142b0ee202)

**Comment by maximthomas** [comment]
Could you provide more info, on how to reproduce the issue, such as OS and docker run command?
I've just run OpenAM Docker container with the command  below and set it up without issues.
```
docker run -h openam-01.domain.com -p 8080:8080 --name openam-01 openidentityplatform/openam
```

**Comment by maximthomas** [comment]
Please provide also your browser info and `/usr/openam/config/install.log` file from your OpenAM Docker container.
