### ISSUE TITLE
Second OIDC authorization request error

### ISSUE THREAD

**Issue by barramandi** [OpenIdentityPlatform/OpenAM#84]
OpenAM version 14.1.8 (OpenAM 14.1.8 Build 900d6316b5 )

Using the openid demo sample from https://github.com/ForgeRock/openid

Setup OIDC provider and OIDC client as per the requirement of the demo.
Start Implicit, login as user, user prompted for consent, and OIDC flow successful for first time.

Redo the Implicit flow again with same browser session, OpenAM will return error to the authorization request

{
  "error_description": "Error running OIDC claims script: java.util.concurrent.ExecutionException: javax.script.ScriptException: javax.script.ScriptException: java.lang.SecurityException: Access to Java class \"java.util.LinkedHashMap$LinkedKeyIterator\" is prohibited.",
  "state": "af0ifjsldkj",
  "error": "not_found"
}

The issue is not present if user logged out before redoing the OIDC login flow

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenAM/pull/86

**Comment by vharseko** [comment]
Configuaration->Scripting-> for all instancess add in Engine Configuration "Java class whitelist" java.util.LinkedHashMap$LinkedKeyIterator

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/14.1.9
