### ISSUE TITLE
Windows 7 Unexpected LDAP exception during "Create Default Configuration"

### ISSUE THREAD

**Issue by ryancogswell** [OpenIdentityPlatform/OpenAM#91]
When creating the default configuration, install fails with "Unexpected LDAP exception occurred".
Here is the install log:
[openam_install.log](https://github.com/OpenIdentityPlatform/OpenAM/files/2462486/openam_install.log)

This seems to be similar to issue #57.

I am using the latest OpenAM release: 14.1.10.

When I debugged into the point where the exception occurs, I found that the exception occurs twice before the install aborts. At the first exception, the bytes in the buffer when it was trying to read an integer were the bytes for the following string:
`ax="String" type="single_choice" > <ChoiceValues> <ChoiceValue i18`
For the second exception the bytes in the buffer were:
`tax="number" type="single">`

In both of these cases, the code was trying to read an integer when the buffer appears to be in the middle of the word "syntax".

I'm running this on Tomcat 9.0.12 using JDK 10.0.2.

**Comment by vharseko** [comment]
downgrade JDK to 1.8 fix problem ?

**Comment by ryancogswell** [comment]
I tried 1.8 first and encountered errors just deploying the web app because at least one of the jars in the war file was using Java 9 byte code version.

**Comment by vharseko** [comment]
- "one of the jars in the war file was using Java 9 byte code version " - please remove webapps content and redeploy openam.war after downgrade jdk
- please check docker version with jdk 1.8: https://hub.docker.com/r/openidentityplatform/openam/

**Comment by ryancogswell** [comment]
When I previously tried JDK 1.8, I was also using Tomcat 7 and I was getting the following error:
SEVERE: Unable to process Jar entry [module-info.class] from Jar [jar:file:/.../WEB-INF/lib/javax.xml.soap-api-1.4.0.jar!/] for annotations
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:133)
	at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:60)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:209)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:119)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2125)

I misinterpreted this as meaning that I needed JDK 9+, so I switched to JDK 11 which forced me to use a new Tomcat as well. It turns out that just switching from Tomcat 7 to Tomcat 9 (with still using JDK 1.8) addresses the error above.
However using Tomcat 9 with JDK 1.8, I still get the same "Unexpected LDAP exception" error as I did with JDK 10.0.2.

**Comment by ryancogswell** [comment]
I'll try to look at the docker version, but I couldn't get to it today.

**Comment by maximthomas** [comment]
@ryancogswell I have just tried JDK 1.8 and latest Tomcat 7.0.91, there were no errors during startup.   `Invalid byte tag in constant pool: 19` error apperars in older Tomcat versions but now it seems to be fixed.

**Comment by ryancogswell** [comment]
Yes, I did eventually try latest Tomcat 7 and that fixed the byte tag error, however I still got the ldap error during Create Default Configuration.

**Comment by maximthomas** [comment]
@ryancogswell Create Default Configuration error with JDK 1.8 and latest Tomcat 7 is the same as in https://github.com/OpenIdentityPlatform/OpenAM/issues/91#issue-368430625?

**Comment by ryancogswell** [comment]
Yes, same error as in the install log for my initial comment on this issue.

**Comment by maximthomas** [comment]
I tried Tomcat 7.0.91 in both JDK 1.8 and 10 version under Ubuntu Linux and Mac, and could not reproduce this issue. Please try to remove or rename `$HOME/openam` folder and try to install OpenAM again or try Docker installation

**Comment by ryancogswell** [comment]
I'm using Windows 7 and no matter what I try I'm still getting this error. I can't install Docker on my machine (because it's Windows 7), but I'll try to experiment with other OS options later today.

**Comment by vharseko** [comment]
@maximthomas please check windows …

**Comment by ryancogswell** [comment]
I just created a new Windows 7 workstation using AWS workspaces.
Installed latest JDK 1.8, latest tomcat 7, and openam 14.1.10 and got the exact same error during Create Default Configuration.

**Comment by ryancogswell** [comment]
@maximthomas I just created a new Windows 10 AWS workspace and installed the exact same pieces as on the Windows 7 workspace, and the Windows 10 "Create Default Configuration" was successful. So Windows 7 fails and Windows 10 works with everything else the same.

**Comment by maximthomas** [comment]
@ryancogswell Yes, i see this issue under Windows 7 too

**Comment by vharseko** [comment]
@ryancogswell  can you attach detailed log with startup option: 
```bash
-Dcom.iplanet.services.debug.level=message -Dcom.sun.services.debug.mergeall=on 
```

**Comment by ryancogswell** [comment]
There are a number of different logs and I'm not certain which ones you care about, so let me know if there is one I didn't include that you want. I've tried to name the zip files to make it clear where they came from. For this run I did no renaming of the war, so "OpenAM-14.1.11" is the webapp name.

[configroot_opends_logs.zip](https://github.com/OpenIdentityPlatform/OpenAM/files/2485095/configroot_opends_logs.zip)
[install.log](https://github.com/OpenIdentityPlatform/OpenAM/files/2485096/install.log)
[tomcatroot_logs.zip](https://github.com/OpenIdentityPlatform/OpenAM/files/2485097/tomcatroot_logs.zip)
[configroot_OpenAM-14.1.11_debug.zip](https://github.com/OpenIdentityPlatform/OpenAM/files/2485102/configroot_OpenAM-14.1.11_debug.zip)

Just let me know if you want me to run it with any additional system properties set. I'd also be willing to debug into parts of it, but I would need a bit of guidance -- I am not at all familiar with the LDAP portion of this code base. I'm mainly familiar with the portion dealing with SAML assertion processing.

**Comment by ryancogswell** [comment]
Just FYI -- I tried this out again with the latest release (14.1.12) and the behavior is unchanged.

**Comment by ryancogswell** [comment]
@vharseko Thanks for your work on this. I now have SAML federation working in our development environment with the latest OpenAM version (our production environment is using version 10).
