### ISSUE TITLE
Build from source fails on W10

### ISSUE THREAD

**Issue by leopal77** [OpenIdentityPlatform/OpenAM#95]
**Describe the bug**
I am trying to build whole project but the building process fails when trying to build `OpenDj` module.

**To Reproduce**
1. I cloned project - `git clone --recursive  https://github.com/OpenIdentityPlatform/OpenAM.git` and configured git to allow longpaths. -> (SUCCESS)
2. `mvn -DskipTests -Dmaven.javadoc.skip=true install -f OpenAM/OpenDJ/forgerock-parent` completes successfully. -> (SUCCESS)
3. The step which fails is `mvn -DskipTests -Dmaven.javadoc.skip=true install -f OpenAM/OpenDJ` . The error I get is:
`[ERROR]   The project org.forgerock.opendj:opendj-core:[unknown-version] (C:\Projects\github-projects\OpenAM\OpenDJ\opendj-core\pom.xml) has 1 error

`[ERROR]     Non-resolvable parent POM for org.forgerock.opendj:opendj-parent:[unknown-version]: Failure to find org.forgerock.opendj:opendj-bom:pom:4.2.2 , 'parent.relativePath' points at wrong local POM @ org.forgerock.opendj:opendj-parent:[unknown-version], C:\Projects\github-projects\OpenAM\OpenDJ\pom.xml, line 20, column 13 ->`

> Note that I get the same error for the rest sub-projects of OpedDj(`opendj-doc-maven-plugin`opendj-grizzly` etc)

**Expected behavior**
Project build should be successfully completed.

**Desktop (please complete the following information):**
 - OS: W10 x64
 - Java8
 - Maven 3.5.0

**Comment by vharseko** [comment]
please check \<version\>4.2.2\</version\> in opendj-bom/pom.xml

**Comment by leopal77** [comment]
Hi vharseko and thanks for your answer,

Version number seems to be ok:
`opendj-bom/pom.xml`:

```
<groupId>org.forgerock.opendj</groupId>
<artifactId>opendj-bom</artifactId>  
<version>4.2.2</version>
```

What else can I try?

**Comment by vharseko** [comment]
please attach build log with -X swith

mvn -X -DskipTests -Dmaven.javadoc.skip=true install -f OpenAM/OpenDJ

----------------------------------------------------------------------------------
ICQ: 11727046 Skype: vharseko Mobile: +7-917-595-51-55

**Comment by leopal77** [comment]
I have attached the log file.

Note that I am using my company's nexus repository along with maven central,  so for privacy reasons I have replaced in the logs the hostname of the nexus server.

[openAM-build.log](https://github.com/OpenIdentityPlatform/OpenAM/files/2494680/openAM-build.log)

**Comment by vharseko** [comment]
please try rebuild all projects:
* with -U switch
* with remove ~/.m2/repository

**Comment by leopal77** [comment]
Retried with proposed workarounds with no luck.

It seems that the build process cannot find the pom of `opendj-bom` or the version that I have is wrong.

Indeed when building of forgerock-parent finishes in my .m2 there is no `pom .xml` for `opendj-bom`

Is opendj-bom published somewhere so I can download and add manually on my .m2?

**Comment by vharseko** [comment]
please try change in OpenDJ/pom.xml
```xml
<relativePath>opendj-bom/pom.xml</relativePath>
```
to
```xml
<relativePath>opendj-bom\pom.xml</relativePath>
```

**Comment by leopal77** [comment]
No luck again.  

Does the build process works on linux hosts?

I am thinking of building the project in a docker container and use a volume to get the m2.

**Comment by vharseko** [comment]
you can check build status: https://travis-ci.org/OpenIdentityPlatform/OpenAM and build scripts https://github.com/OpenIdentityPlatform/OpenAM/blob/master/.travis.yml 
also build tested on windows 7
@maximthomas  can you check build on Win10 ?

**Comment by maximthomas** [comment]
Ok, i'll try to check soon

**Comment by leopal77** [comment]
Thank you guys for the effort.

@maximthomas Waiting your response!

**Comment by maximthomas** [comment]
@leopal77, I've just reproduced this issue, but couldn't fixed it yet as workaround I suggest before build OpenDJ, exec `mvn install -f OpenAM/OpenDJ/opendj-bom` command

**Comment by leopal77** [comment]
Yeah the issue seems to be related with `opendj-bom` module. For some reason it is not installed the moment the build process need it.

My workaround was to build the project in a docker container, get `opendj-bom` pom.xml from container's `.m2` and add it on my host's machine `.m2`.

After doing this the build process finished successfully. I assume that your workaround is much more simpler.

**Comment by maximthomas** [comment]
@leopal77 I've tried to downgrade maven to 3.3.9 and it works fine in Win 10, I think there's issue in maven  3.5.4
