### ISSUE TITLE
Quick start guide is incorrect.

### ISSUE THREAD

**Issue by vharseko** [OpenIdentityPlatform/OpenAM#96]
@ahavriluk First of all you have to specify port when you setup resource. Second you don't use name WebAgent - it won't work. You need to name it apache_agent. Then you have to make sure docker containers can talk to each other (--net host option?). Oh, yeah, apache_agent doesn't work on Mac.

**Comment by maximthomas** [comment]
fixed https://github.com/OpenIdentityPlatform/OpenAM/wiki/Quick-Start-Guide

**Comment by ahavriluk** [comment]
Have you tested it?

**Comment by vharseko** [comment]
@ahavriluk  Where do you see the error?

**Comment by vharseko** [comment]
closed due to inactivity
